/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AIOptimizerModelSpecsInitParameters struct {

	// (String) Model description.
	// Model description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Block List, Max: 1) HuggingFace registry configuration. Required when registry_type is HUGGING_FACE. (see below for nested schema)
	// HuggingFace registry configuration. Required when registry_type is HUGGING_FACE.
	Huggingface []HuggingfaceInitParameters `json:"huggingface,omitempty" tf:"huggingface,omitempty"`

	// (String) Model name.
	// Model name.
	Model *string `json:"model,omitempty" tf:"model,omitempty"`

	// (Block List, Max: 1) Private registry configuration. Required when registry_type is PRIVATE. (see below for nested schema)
	// Private registry configuration. Required when registry_type is PRIVATE.
	PrivateRegistry []PrivateRegistryInitParameters `json:"privateRegistry,omitempty" tf:"private_registry,omitempty"`

	// (String) Registry type: HUGGING_FACE or PRIVATE.
	// Registry type: HUGGING_FACE or PRIVATE.
	RegistryType *string `json:"registryType,omitempty" tf:"registry_type,omitempty"`

	// (Boolean) Whether the model is routable.
	// Whether the model is routable.
	Routable *bool `json:"routable,omitempty" tf:"routable,omitempty"`

	// (String) Model type (chat, embeddings, completion, etc.).
	// Model type (chat, embeddings, completion, etc.).
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type AIOptimizerModelSpecsObservation struct {

	// (String) Model description.
	// Model description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Block List, Max: 1) HuggingFace registry configuration. Required when registry_type is HUGGING_FACE. (see below for nested schema)
	// HuggingFace registry configuration. Required when registry_type is HUGGING_FACE.
	Huggingface []HuggingfaceObservation `json:"huggingface,omitempty" tf:"huggingface,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Model name.
	// Model name.
	Model *string `json:"model,omitempty" tf:"model,omitempty"`

	// (Block List, Max: 1) Private registry configuration. Required when registry_type is PRIVATE. (see below for nested schema)
	// Private registry configuration. Required when registry_type is PRIVATE.
	PrivateRegistry []PrivateRegistryObservation `json:"privateRegistry,omitempty" tf:"private_registry,omitempty"`

	// (String) Registry type: HUGGING_FACE or PRIVATE.
	// Registry type: HUGGING_FACE or PRIVATE.
	RegistryType *string `json:"registryType,omitempty" tf:"registry_type,omitempty"`

	// (Boolean) Whether the model is routable.
	// Whether the model is routable.
	Routable *bool `json:"routable,omitempty" tf:"routable,omitempty"`

	// (String) Model type (chat, embeddings, completion, etc.).
	// Model type (chat, embeddings, completion, etc.).
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type AIOptimizerModelSpecsParameters struct {

	// (String) Model description.
	// Model description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Block List, Max: 1) HuggingFace registry configuration. Required when registry_type is HUGGING_FACE. (see below for nested schema)
	// HuggingFace registry configuration. Required when registry_type is HUGGING_FACE.
	// +kubebuilder:validation:Optional
	Huggingface []HuggingfaceParameters `json:"huggingface,omitempty" tf:"huggingface,omitempty"`

	// (String) Model name.
	// Model name.
	// +kubebuilder:validation:Optional
	Model *string `json:"model,omitempty" tf:"model,omitempty"`

	// (Block List, Max: 1) Private registry configuration. Required when registry_type is PRIVATE. (see below for nested schema)
	// Private registry configuration. Required when registry_type is PRIVATE.
	// +kubebuilder:validation:Optional
	PrivateRegistry []PrivateRegistryParameters `json:"privateRegistry,omitempty" tf:"private_registry,omitempty"`

	// (String) Registry type: HUGGING_FACE or PRIVATE.
	// Registry type: HUGGING_FACE or PRIVATE.
	// +kubebuilder:validation:Optional
	RegistryType *string `json:"registryType,omitempty" tf:"registry_type,omitempty"`

	// (Boolean) Whether the model is routable.
	// Whether the model is routable.
	// +kubebuilder:validation:Optional
	Routable *bool `json:"routable,omitempty" tf:"routable,omitempty"`

	// (String) Model type (chat, embeddings, completion, etc.).
	// Model type (chat, embeddings, completion, etc.).
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type HuggingfaceInitParameters struct {

	// llama/Llama-3.1-8B-Instruct).
	// HuggingFace model name (e.g. meta-llama/Llama-3.1-8B-Instruct).
	ModelName *string `json:"modelName,omitempty" tf:"model_name,omitempty"`
}

type HuggingfaceObservation struct {

	// llama/Llama-3.1-8B-Instruct).
	// HuggingFace model name (e.g. meta-llama/Llama-3.1-8B-Instruct).
	ModelName *string `json:"modelName,omitempty" tf:"model_name,omitempty"`
}

type HuggingfaceParameters struct {

	// llama/Llama-3.1-8B-Instruct).
	// HuggingFace model name (e.g. meta-llama/Llama-3.1-8B-Instruct).
	// +kubebuilder:validation:Optional
	ModelName *string `json:"modelName" tf:"model_name,omitempty"`
}

type PrivateRegistryInitParameters struct {

	// (String) Base model identifier.
	// Base model identifier.
	BaseModelID *string `json:"baseModelId,omitempty" tf:"base_model_id,omitempty"`

	// (String) ID of the castai_ai_optimizer_model_registry resource.
	// ID of the castai_ai_optimizer_model_registry resource.
	RegistryID *string `json:"registryId,omitempty" tf:"registry_id,omitempty"`
}

type PrivateRegistryObservation struct {

	// (String) Base model identifier.
	// Base model identifier.
	BaseModelID *string `json:"baseModelId,omitempty" tf:"base_model_id,omitempty"`

	// (String) ID of the castai_ai_optimizer_model_registry resource.
	// ID of the castai_ai_optimizer_model_registry resource.
	RegistryID *string `json:"registryId,omitempty" tf:"registry_id,omitempty"`
}

type PrivateRegistryParameters struct {

	// (String) Base model identifier.
	// Base model identifier.
	// +kubebuilder:validation:Optional
	BaseModelID *string `json:"baseModelId" tf:"base_model_id,omitempty"`

	// (String) ID of the castai_ai_optimizer_model_registry resource.
	// ID of the castai_ai_optimizer_model_registry resource.
	// +kubebuilder:validation:Optional
	RegistryID *string `json:"registryId" tf:"registry_id,omitempty"`
}

// AIOptimizerModelSpecsSpec defines the desired state of AIOptimizerModelSpecs
type AIOptimizerModelSpecsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AIOptimizerModelSpecsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AIOptimizerModelSpecsInitParameters `json:"initProvider,omitempty"`
}

// AIOptimizerModelSpecsStatus defines the observed state of AIOptimizerModelSpecs.
type AIOptimizerModelSpecsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AIOptimizerModelSpecsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AIOptimizerModelSpecs is the Schema for the AIOptimizerModelSpecss API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,castai}
type AIOptimizerModelSpecs struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.model) || (has(self.initProvider) && has(self.initProvider.model))",message="spec.forProvider.model is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.registryType) || (has(self.initProvider) && has(self.initProvider.registryType))",message="spec.forProvider.registryType is a required parameter"
	Spec   AIOptimizerModelSpecsSpec   `json:"spec"`
	Status AIOptimizerModelSpecsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AIOptimizerModelSpecsList contains a list of AIOptimizerModelSpecss
type AIOptimizerModelSpecsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AIOptimizerModelSpecs `json:"items"`
}

// Repository type metadata.
var (
	AIOptimizerModelSpecs_Kind             = "AIOptimizerModelSpecs"
	AIOptimizerModelSpecs_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AIOptimizerModelSpecs_Kind}.String()
	AIOptimizerModelSpecs_KindAPIVersion   = AIOptimizerModelSpecs_Kind + "." + CRDGroupVersion.String()
	AIOptimizerModelSpecs_GroupVersionKind = CRDGroupVersion.WithKind(AIOptimizerModelSpecs_Kind)
)

func init() {
	SchemeBuilder.Register(&AIOptimizerModelSpecs{}, &AIOptimizerModelSpecsList{})
}
