/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AcceleratorsInitParameters struct {

	// (Number) Number of accelerators of this type per VM.
	// Number of accelerators of this type per VM.
	AcceleratorCount *float64 `json:"acceleratorCount,omitempty" tf:"accelerator_count,omitempty"`

	// (String) Accelerator (GPU) type as the full GCP acceleratorType URL.
	// Accelerator (GPU) type as the full GCP acceleratorType URL.
	AcceleratorType *string `json:"acceleratorType,omitempty" tf:"accelerator_type,omitempty"`
}

type AcceleratorsObservation struct {

	// (Number) Number of accelerators of this type per VM.
	// Number of accelerators of this type per VM.
	AcceleratorCount *float64 `json:"acceleratorCount,omitempty" tf:"accelerator_count,omitempty"`

	// (String) Accelerator (GPU) type as the full GCP acceleratorType URL.
	// Accelerator (GPU) type as the full GCP acceleratorType URL.
	AcceleratorType *string `json:"acceleratorType,omitempty" tf:"accelerator_type,omitempty"`
}

type AcceleratorsParameters struct {

	// (Number) Number of accelerators of this type per VM.
	// Number of accelerators of this type per VM.
	// +kubebuilder:validation:Optional
	AcceleratorCount *float64 `json:"acceleratorCount" tf:"accelerator_count,omitempty"`

	// (String) Accelerator (GPU) type as the full GCP acceleratorType URL.
	// Accelerator (GPU) type as the full GCP acceleratorType URL.
	// +kubebuilder:validation:Optional
	AcceleratorType *string `json:"acceleratorType" tf:"accelerator_type,omitempty"`
}

type AwsCapacityBlockDetailsInitParameters struct {

	// (String) Availability zone name.
	// Availability zone name.
	AvailabilityZone *string `json:"availabilityZone,omitempty" tf:"availability_zone,omitempty"`

	// (String) Availability zone ID.
	// Availability zone ID.
	AvailabilityZoneID *string `json:"availabilityZoneId,omitempty" tf:"availability_zone_id,omitempty"`

	// (Number) Available (unused) instance count.
	// Available (unused) instance count.
	AvailableInstanceCount *float64 `json:"availableInstanceCount,omitempty" tf:"available_instance_count,omitempty"`

	// (String) Capacity block reservation ID.
	// Capacity block reservation ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Instance platform (e.g. Linux/UNIX).
	// Instance platform (e.g. Linux/UNIX).
	InstancePlatform *string `json:"instancePlatform,omitempty" tf:"instance_platform,omitempty"`

	// (String) EC2 instance type.
	// EC2 instance type.
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// (String) Capacity block state.
	// Capacity block state.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (Number) Total reserved instance count.
	// Total reserved instance count.
	TotalInstanceCount *float64 `json:"totalInstanceCount,omitempty" tf:"total_instance_count,omitempty"`
}

type AwsCapacityBlockDetailsObservation struct {

	// (String) Availability zone name.
	// Availability zone name.
	AvailabilityZone *string `json:"availabilityZone,omitempty" tf:"availability_zone,omitempty"`

	// (String) Availability zone ID.
	// Availability zone ID.
	AvailabilityZoneID *string `json:"availabilityZoneId,omitempty" tf:"availability_zone_id,omitempty"`

	// (Number) Available (unused) instance count.
	// Available (unused) instance count.
	AvailableInstanceCount *float64 `json:"availableInstanceCount,omitempty" tf:"available_instance_count,omitempty"`

	// (String) Capacity block reservation ID.
	// Capacity block reservation ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Instance platform (e.g. Linux/UNIX).
	// Instance platform (e.g. Linux/UNIX).
	InstancePlatform *string `json:"instancePlatform,omitempty" tf:"instance_platform,omitempty"`

	// (String) EC2 instance type.
	// EC2 instance type.
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// (String) Capacity block state.
	// Capacity block state.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (Number) Total reserved instance count.
	// Total reserved instance count.
	TotalInstanceCount *float64 `json:"totalInstanceCount,omitempty" tf:"total_instance_count,omitempty"`
}

type AwsCapacityBlockDetailsParameters struct {

	// (String) Availability zone name.
	// Availability zone name.
	// +kubebuilder:validation:Optional
	AvailabilityZone *string `json:"availabilityZone,omitempty" tf:"availability_zone,omitempty"`

	// (String) Availability zone ID.
	// Availability zone ID.
	// +kubebuilder:validation:Optional
	AvailabilityZoneID *string `json:"availabilityZoneId,omitempty" tf:"availability_zone_id,omitempty"`

	// (Number) Available (unused) instance count.
	// Available (unused) instance count.
	// +kubebuilder:validation:Optional
	AvailableInstanceCount *float64 `json:"availableInstanceCount,omitempty" tf:"available_instance_count,omitempty"`

	// (String) Capacity block reservation ID.
	// Capacity block reservation ID.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// (String) Instance platform (e.g. Linux/UNIX).
	// Instance platform (e.g. Linux/UNIX).
	// +kubebuilder:validation:Optional
	InstancePlatform *string `json:"instancePlatform,omitempty" tf:"instance_platform,omitempty"`

	// (String) EC2 instance type.
	// EC2 instance type.
	// +kubebuilder:validation:Optional
	InstanceType *string `json:"instanceType" tf:"instance_type,omitempty"`

	// (String) Capacity block state.
	// Capacity block state.
	// +kubebuilder:validation:Optional
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (Number) Total reserved instance count.
	// Total reserved instance count.
	// +kubebuilder:validation:Optional
	TotalInstanceCount *float64 `json:"totalInstanceCount" tf:"total_instance_count,omitempty"`
}

type AwsOdcrDetailsInitParameters struct {

	// (String) Availability zone name.
	// Availability zone name.
	AvailabilityZone *string `json:"availabilityZone,omitempty" tf:"availability_zone,omitempty"`

	// (String) Availability zone ID.
	// Availability zone ID.
	AvailabilityZoneID *string `json:"availabilityZoneId,omitempty" tf:"availability_zone_id,omitempty"`

	// (Number) Available (unused) instance count.
	// Available (unused) instance count.
	AvailableInstanceCount *float64 `json:"availableInstanceCount,omitempty" tf:"available_instance_count,omitempty"`

	// (String) End date type (unlimited, limited).
	// End date type (unlimited, limited).
	EndDateType *string `json:"endDateType,omitempty" tf:"end_date_type,omitempty"`

	// (String) Commitment ID.
	// Capacity reservation ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Instance match criteria (open, targeted).
	// Instance match criteria (open, targeted).
	InstanceMatchCriteria *string `json:"instanceMatchCriteria,omitempty" tf:"instance_match_criteria,omitempty"`

	// (String) Instance platform (e.g. Linux/UNIX).
	// Instance platform (e.g. Linux/UNIX).
	InstancePlatform *string `json:"instancePlatform,omitempty" tf:"instance_platform,omitempty"`

	// (String) EC2 instance type.
	// EC2 instance type.
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// (Boolean) Whether this reservation is interruptible.
	// Whether this reservation is interruptible.
	Interruptible *bool `json:"interruptible,omitempty" tf:"interruptible,omitempty"`

	// (String) Computed lifecycle state of the commitment.
	// Capacity reservation state.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (String) Tenancy (default, dedicated).
	// Tenancy (default, dedicated).
	Tenancy *string `json:"tenancy,omitempty" tf:"tenancy,omitempty"`

	// (Number) Total reserved instance count.
	// Total reserved instance count.
	TotalInstanceCount *float64 `json:"totalInstanceCount,omitempty" tf:"total_instance_count,omitempty"`
}

type AwsOdcrDetailsObservation struct {

	// (String) Availability zone name.
	// Availability zone name.
	AvailabilityZone *string `json:"availabilityZone,omitempty" tf:"availability_zone,omitempty"`

	// (String) Availability zone ID.
	// Availability zone ID.
	AvailabilityZoneID *string `json:"availabilityZoneId,omitempty" tf:"availability_zone_id,omitempty"`

	// (Number) Available (unused) instance count.
	// Available (unused) instance count.
	AvailableInstanceCount *float64 `json:"availableInstanceCount,omitempty" tf:"available_instance_count,omitempty"`

	// (String) End date type (unlimited, limited).
	// End date type (unlimited, limited).
	EndDateType *string `json:"endDateType,omitempty" tf:"end_date_type,omitempty"`

	// (String) Commitment ID.
	// Capacity reservation ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Instance match criteria (open, targeted).
	// Instance match criteria (open, targeted).
	InstanceMatchCriteria *string `json:"instanceMatchCriteria,omitempty" tf:"instance_match_criteria,omitempty"`

	// (String) Instance platform (e.g. Linux/UNIX).
	// Instance platform (e.g. Linux/UNIX).
	InstancePlatform *string `json:"instancePlatform,omitempty" tf:"instance_platform,omitempty"`

	// (String) EC2 instance type.
	// EC2 instance type.
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// (Boolean) Whether this reservation is interruptible.
	// Whether this reservation is interruptible.
	Interruptible *bool `json:"interruptible,omitempty" tf:"interruptible,omitempty"`

	// (String) Computed lifecycle state of the commitment.
	// Capacity reservation state.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (String) Tenancy (default, dedicated).
	// Tenancy (default, dedicated).
	Tenancy *string `json:"tenancy,omitempty" tf:"tenancy,omitempty"`

	// (Number) Total reserved instance count.
	// Total reserved instance count.
	TotalInstanceCount *float64 `json:"totalInstanceCount,omitempty" tf:"total_instance_count,omitempty"`
}

type AwsOdcrDetailsParameters struct {

	// (String) Availability zone name.
	// Availability zone name.
	// +kubebuilder:validation:Optional
	AvailabilityZone *string `json:"availabilityZone,omitempty" tf:"availability_zone,omitempty"`

	// (String) Availability zone ID.
	// Availability zone ID.
	// +kubebuilder:validation:Optional
	AvailabilityZoneID *string `json:"availabilityZoneId,omitempty" tf:"availability_zone_id,omitempty"`

	// (Number) Available (unused) instance count.
	// Available (unused) instance count.
	// +kubebuilder:validation:Optional
	AvailableInstanceCount *float64 `json:"availableInstanceCount,omitempty" tf:"available_instance_count,omitempty"`

	// (String) End date type (unlimited, limited).
	// End date type (unlimited, limited).
	// +kubebuilder:validation:Optional
	EndDateType *string `json:"endDateType,omitempty" tf:"end_date_type,omitempty"`

	// (String) Commitment ID.
	// Capacity reservation ID.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// (String) Instance match criteria (open, targeted).
	// Instance match criteria (open, targeted).
	// +kubebuilder:validation:Optional
	InstanceMatchCriteria *string `json:"instanceMatchCriteria,omitempty" tf:"instance_match_criteria,omitempty"`

	// (String) Instance platform (e.g. Linux/UNIX).
	// Instance platform (e.g. Linux/UNIX).
	// +kubebuilder:validation:Optional
	InstancePlatform *string `json:"instancePlatform,omitempty" tf:"instance_platform,omitempty"`

	// (String) EC2 instance type.
	// EC2 instance type.
	// +kubebuilder:validation:Optional
	InstanceType *string `json:"instanceType" tf:"instance_type,omitempty"`

	// (Boolean) Whether this reservation is interruptible.
	// Whether this reservation is interruptible.
	// +kubebuilder:validation:Optional
	Interruptible *bool `json:"interruptible,omitempty" tf:"interruptible,omitempty"`

	// (String) Computed lifecycle state of the commitment.
	// Capacity reservation state.
	// +kubebuilder:validation:Optional
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (String) Tenancy (default, dedicated).
	// Tenancy (default, dedicated).
	// +kubebuilder:validation:Optional
	Tenancy *string `json:"tenancy,omitempty" tf:"tenancy,omitempty"`

	// (Number) Total reserved instance count.
	// Total reserved instance count.
	// +kubebuilder:validation:Optional
	TotalInstanceCount *float64 `json:"totalInstanceCount" tf:"total_instance_count,omitempty"`
}

type AwsReservedInstancesDetailsInitParameters struct {

	// (String) Availability zone ID.
	// AWS availability zone ID (zonal RIs only).
	AvailabilityZoneID *string `json:"availabilityZoneId,omitempty" tf:"availability_zone_id,omitempty"`

	// (String) AWS availability zone name (zonal RIs only).
	// AWS availability zone name (zonal RIs only).
	AvailabilityZoneName *string `json:"availabilityZoneName,omitempty" tf:"availability_zone_name,omitempty"`

	// (String) Commitment ID.
	// AWS reserved instance ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Number) Instance count.
	// Instance count.
	InstanceCount *float64 `json:"instanceCount,omitempty" tf:"instance_count,omitempty"`

	// (String) EC2 instance type.
	// AWS EC2 instance type.
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// (String) Scope: whether the commitment applies to a region or an availability zone.
	// Scope: whether the commitment applies to a region or an availability zone.
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// (String) Computed lifecycle state of the commitment.
	// Reserved instance state (e.g. active).
	State *string `json:"state,omitempty" tf:"state,omitempty"`
}

type AwsReservedInstancesDetailsObservation struct {

	// (String) Availability zone ID.
	// AWS availability zone ID (zonal RIs only).
	AvailabilityZoneID *string `json:"availabilityZoneId,omitempty" tf:"availability_zone_id,omitempty"`

	// (String) AWS availability zone name (zonal RIs only).
	// AWS availability zone name (zonal RIs only).
	AvailabilityZoneName *string `json:"availabilityZoneName,omitempty" tf:"availability_zone_name,omitempty"`

	// (String) Commitment ID.
	// AWS reserved instance ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Number) Instance count.
	// Instance count.
	InstanceCount *float64 `json:"instanceCount,omitempty" tf:"instance_count,omitempty"`

	// (String) EC2 instance type.
	// AWS EC2 instance type.
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// (String) Scope: whether the commitment applies to a region or an availability zone.
	// Scope: whether the commitment applies to a region or an availability zone.
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// (String) Computed lifecycle state of the commitment.
	// Reserved instance state (e.g. active).
	State *string `json:"state,omitempty" tf:"state,omitempty"`
}

type AwsReservedInstancesDetailsParameters struct {

	// (String) Availability zone ID.
	// AWS availability zone ID (zonal RIs only).
	// +kubebuilder:validation:Optional
	AvailabilityZoneID *string `json:"availabilityZoneId,omitempty" tf:"availability_zone_id,omitempty"`

	// (String) AWS availability zone name (zonal RIs only).
	// AWS availability zone name (zonal RIs only).
	// +kubebuilder:validation:Optional
	AvailabilityZoneName *string `json:"availabilityZoneName,omitempty" tf:"availability_zone_name,omitempty"`

	// (String) Commitment ID.
	// AWS reserved instance ID.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// (Number) Instance count.
	// Instance count.
	// +kubebuilder:validation:Optional
	InstanceCount *float64 `json:"instanceCount" tf:"instance_count,omitempty"`

	// (String) EC2 instance type.
	// AWS EC2 instance type.
	// +kubebuilder:validation:Optional
	InstanceType *string `json:"instanceType" tf:"instance_type,omitempty"`

	// (String) Scope: whether the commitment applies to a region or an availability zone.
	// Scope: whether the commitment applies to a region or an availability zone.
	// +kubebuilder:validation:Optional
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// (String) Computed lifecycle state of the commitment.
	// Reserved instance state (e.g. active).
	// +kubebuilder:validation:Optional
	State *string `json:"state,omitempty" tf:"state,omitempty"`
}

type AwsSavingsPlanDetailsInitParameters struct {

	// (Number) Commitment amount in USD per hour.
	// Commitment amount in USD per hour.
	CommitmentAmount *float64 `json:"commitmentAmount,omitempty" tf:"commitment_amount,omitempty"`

	// (String) Commitment term. One of: COMMITMENT_TERM_UNIT_ONE_YEAR, COMMITMENT_TERM_UNIT_THREE_YEARS.
	// Commitment term. One of: COMMITMENT_TERM_UNIT_ONE_YEAR, COMMITMENT_TERM_UNIT_THREE_YEARS.
	CommitmentTerm *string `json:"commitmentTerm,omitempty" tf:"commitment_term,omitempty"`

	// (String) Commitment ID.
	// AWS savings plan ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Instance type family (EC2 instance savings plans).
	// Instance type family (EC2 instance savings plans).
	InstanceTypeFamily *string `json:"instanceTypeFamily,omitempty" tf:"instance_type_family,omitempty"`

	// (String) AWS savings plan offering ID.
	// AWS savings plan offering ID.
	OfferingID *string `json:"offeringId,omitempty" tf:"offering_id,omitempty"`

	// (String) Payment option. One of: ALL_UPFRONT, PARTIAL_UPFRONT, NO_UPFRONT.
	// Payment option. One of: ALL_UPFRONT, PARTIAL_UPFRONT, NO_UPFRONT.
	PaymentOption *string `json:"paymentOption,omitempty" tf:"payment_option,omitempty"`

	// (String) Region where the commitment is applicable.
	// Savings plan region.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) Computed lifecycle state of the commitment.
	// Savings plan state (e.g. active).
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (String) Commitment type. One of: RESERVED_INSTANCE, RESOURCE_CUD, SAVINGS_PLAN, CAPACITY_BLOCK, ON_DEMAND_CAPACITY_RESERVATION, FLEX_CUD. The matching details block must be set.
	// Savings plan type (e.g. Compute, EC2Instance).
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type AwsSavingsPlanDetailsObservation struct {

	// (Number) Commitment amount in USD per hour.
	// Commitment amount in USD per hour.
	CommitmentAmount *float64 `json:"commitmentAmount,omitempty" tf:"commitment_amount,omitempty"`

	// (String) Commitment term. One of: COMMITMENT_TERM_UNIT_ONE_YEAR, COMMITMENT_TERM_UNIT_THREE_YEARS.
	// Commitment term. One of: COMMITMENT_TERM_UNIT_ONE_YEAR, COMMITMENT_TERM_UNIT_THREE_YEARS.
	CommitmentTerm *string `json:"commitmentTerm,omitempty" tf:"commitment_term,omitempty"`

	// (String) Commitment ID.
	// AWS savings plan ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Instance type family (EC2 instance savings plans).
	// Instance type family (EC2 instance savings plans).
	InstanceTypeFamily *string `json:"instanceTypeFamily,omitempty" tf:"instance_type_family,omitempty"`

	// (String) AWS savings plan offering ID.
	// AWS savings plan offering ID.
	OfferingID *string `json:"offeringId,omitempty" tf:"offering_id,omitempty"`

	// (String) Payment option. One of: ALL_UPFRONT, PARTIAL_UPFRONT, NO_UPFRONT.
	// Payment option. One of: ALL_UPFRONT, PARTIAL_UPFRONT, NO_UPFRONT.
	PaymentOption *string `json:"paymentOption,omitempty" tf:"payment_option,omitempty"`

	// (String) Region where the commitment is applicable.
	// Savings plan region.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) Computed lifecycle state of the commitment.
	// Savings plan state (e.g. active).
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (String) Commitment type. One of: RESERVED_INSTANCE, RESOURCE_CUD, SAVINGS_PLAN, CAPACITY_BLOCK, ON_DEMAND_CAPACITY_RESERVATION, FLEX_CUD. The matching details block must be set.
	// Savings plan type (e.g. Compute, EC2Instance).
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type AwsSavingsPlanDetailsParameters struct {

	// (Number) Commitment amount in USD per hour.
	// Commitment amount in USD per hour.
	// +kubebuilder:validation:Optional
	CommitmentAmount *float64 `json:"commitmentAmount,omitempty" tf:"commitment_amount,omitempty"`

	// (String) Commitment term. One of: COMMITMENT_TERM_UNIT_ONE_YEAR, COMMITMENT_TERM_UNIT_THREE_YEARS.
	// Commitment term. One of: COMMITMENT_TERM_UNIT_ONE_YEAR, COMMITMENT_TERM_UNIT_THREE_YEARS.
	// +kubebuilder:validation:Optional
	CommitmentTerm *string `json:"commitmentTerm,omitempty" tf:"commitment_term,omitempty"`

	// (String) Commitment ID.
	// AWS savings plan ID.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// (String) Instance type family (EC2 instance savings plans).
	// Instance type family (EC2 instance savings plans).
	// +kubebuilder:validation:Optional
	InstanceTypeFamily *string `json:"instanceTypeFamily,omitempty" tf:"instance_type_family,omitempty"`

	// (String) AWS savings plan offering ID.
	// AWS savings plan offering ID.
	// +kubebuilder:validation:Optional
	OfferingID *string `json:"offeringId,omitempty" tf:"offering_id,omitempty"`

	// (String) Payment option. One of: ALL_UPFRONT, PARTIAL_UPFRONT, NO_UPFRONT.
	// Payment option. One of: ALL_UPFRONT, PARTIAL_UPFRONT, NO_UPFRONT.
	// +kubebuilder:validation:Optional
	PaymentOption *string `json:"paymentOption,omitempty" tf:"payment_option,omitempty"`

	// (String) Region where the commitment is applicable.
	// Savings plan region.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) Computed lifecycle state of the commitment.
	// Savings plan state (e.g. active).
	// +kubebuilder:validation:Optional
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (String) Commitment type. One of: RESERVED_INSTANCE, RESOURCE_CUD, SAVINGS_PLAN, CAPACITY_BLOCK, ON_DEMAND_CAPACITY_RESERVATION, FLEX_CUD. The matching details block must be set.
	// Savings plan type (e.g. Compute, EC2Instance).
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type AzureReservationDetailsInitParameters struct {

	// (Number) Count of reserved instances.
	// Count of reserved instances.
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// (String) Commitment ID.
	// Reservation ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Instance flexibility. One of: ON, OFF.
	// Instance flexibility. One of: ON, OFF.
	InstanceFlexibility *string `json:"instanceFlexibility,omitempty" tf:"instance_flexibility,omitempty"`

	// (String) EC2 instance type.
	// Reserved instance type.
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// (String) Reservation term plan. One of: ONE_YEAR, THREE_YEAR.
	// Reservation term plan. One of: ONE_YEAR, THREE_YEAR.
	Plan *string `json:"plan,omitempty" tf:"plan,omitempty"`

	// (String) Purchase time (RFC3339).
	// Purchase time (RFC3339).
	PurchaseTime *string `json:"purchaseTime,omitempty" tf:"purchase_time,omitempty"`

	// (String) Scope: whether the commitment applies to a region or an availability zone.
	// Scope (e.g. Shared, Single, ManagementGroup).
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// (String) Scope management group.
	// Scope management group.
	ScopeManagementGroup *string `json:"scopeManagementGroup,omitempty" tf:"scope_management_group,omitempty"`

	// (String) Scope resource group.
	// Scope resource group.
	ScopeResourceGroup *string `json:"scopeResourceGroup,omitempty" tf:"scope_resource_group,omitempty"`

	// (String) Scope subscription.
	// Scope subscription.
	ScopeSubscription *string `json:"scopeSubscription,omitempty" tf:"scope_subscription,omitempty"`

	// (String) Scope tenant ID.
	// Scope tenant ID.
	ScopeTenant *string `json:"scopeTenant,omitempty" tf:"scope_tenant,omitempty"`

	// (String) Provisioning state (e.g. Succeeded).
	// Provisioning state (e.g. Succeeded).
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type AzureReservationDetailsObservation struct {

	// (Number) Count of reserved instances.
	// Count of reserved instances.
	Count *float64 `json:"count,omitempty" tf:"count,omitempty"`

	// (String) Commitment ID.
	// Reservation ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Instance flexibility. One of: ON, OFF.
	// Instance flexibility. One of: ON, OFF.
	InstanceFlexibility *string `json:"instanceFlexibility,omitempty" tf:"instance_flexibility,omitempty"`

	// (String) EC2 instance type.
	// Reserved instance type.
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// (String) Reservation term plan. One of: ONE_YEAR, THREE_YEAR.
	// Reservation term plan. One of: ONE_YEAR, THREE_YEAR.
	Plan *string `json:"plan,omitempty" tf:"plan,omitempty"`

	// (String) Purchase time (RFC3339).
	// Purchase time (RFC3339).
	PurchaseTime *string `json:"purchaseTime,omitempty" tf:"purchase_time,omitempty"`

	// (String) Scope: whether the commitment applies to a region or an availability zone.
	// Scope (e.g. Shared, Single, ManagementGroup).
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// (String) Scope management group.
	// Scope management group.
	ScopeManagementGroup *string `json:"scopeManagementGroup,omitempty" tf:"scope_management_group,omitempty"`

	// (String) Scope resource group.
	// Scope resource group.
	ScopeResourceGroup *string `json:"scopeResourceGroup,omitempty" tf:"scope_resource_group,omitempty"`

	// (String) Scope subscription.
	// Scope subscription.
	ScopeSubscription *string `json:"scopeSubscription,omitempty" tf:"scope_subscription,omitempty"`

	// (String) Scope tenant ID.
	// Scope tenant ID.
	ScopeTenant *string `json:"scopeTenant,omitempty" tf:"scope_tenant,omitempty"`

	// (String) Provisioning state (e.g. Succeeded).
	// Provisioning state (e.g. Succeeded).
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type AzureReservationDetailsParameters struct {

	// (Number) Count of reserved instances.
	// Count of reserved instances.
	// +kubebuilder:validation:Optional
	Count *float64 `json:"count" tf:"count,omitempty"`

	// (String) Commitment ID.
	// Reservation ID.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// (String) Instance flexibility. One of: ON, OFF.
	// Instance flexibility. One of: ON, OFF.
	// +kubebuilder:validation:Optional
	InstanceFlexibility *string `json:"instanceFlexibility,omitempty" tf:"instance_flexibility,omitempty"`

	// (String) EC2 instance type.
	// Reserved instance type.
	// +kubebuilder:validation:Optional
	InstanceType *string `json:"instanceType" tf:"instance_type,omitempty"`

	// (String) Reservation term plan. One of: ONE_YEAR, THREE_YEAR.
	// Reservation term plan. One of: ONE_YEAR, THREE_YEAR.
	// +kubebuilder:validation:Optional
	Plan *string `json:"plan,omitempty" tf:"plan,omitempty"`

	// (String) Purchase time (RFC3339).
	// Purchase time (RFC3339).
	// +kubebuilder:validation:Optional
	PurchaseTime *string `json:"purchaseTime,omitempty" tf:"purchase_time,omitempty"`

	// (String) Scope: whether the commitment applies to a region or an availability zone.
	// Scope (e.g. Shared, Single, ManagementGroup).
	// +kubebuilder:validation:Optional
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// (String) Scope management group.
	// Scope management group.
	// +kubebuilder:validation:Optional
	ScopeManagementGroup *string `json:"scopeManagementGroup,omitempty" tf:"scope_management_group,omitempty"`

	// (String) Scope resource group.
	// Scope resource group.
	// +kubebuilder:validation:Optional
	ScopeResourceGroup *string `json:"scopeResourceGroup,omitempty" tf:"scope_resource_group,omitempty"`

	// (String) Scope subscription.
	// Scope subscription.
	// +kubebuilder:validation:Optional
	ScopeSubscription *string `json:"scopeSubscription,omitempty" tf:"scope_subscription,omitempty"`

	// (String) Scope tenant ID.
	// Scope tenant ID.
	// +kubebuilder:validation:Optional
	ScopeTenant *string `json:"scopeTenant,omitempty" tf:"scope_tenant,omitempty"`

	// (String) Provisioning state (e.g. Succeeded).
	// Provisioning state (e.g. Succeeded).
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type AzureSavingsPlanDetailsInitParameters struct {

	// (Number) Commitment amount in USD per hour.
	// Hourly commitment amount in USD per hour.
	CommitmentAmount *float64 `json:"commitmentAmount,omitempty" tf:"commitment_amount,omitempty"`

	// (String) Commitment ID.
	// Savings plan ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Provisioning state (e.g. Succeeded, Expired, Cancelled).
	// Provisioning state (e.g. Succeeded, Expired, Cancelled).
	ProvisioningState *string `json:"provisioningState,omitempty" tf:"provisioning_state,omitempty"`

	// (String) Scope: whether the commitment applies to a region or an availability zone.
	// Applied scope type. One of: SINGLE, SHARED, MANAGEMENT_GROUP.
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// (String) Scope management group.
	// Scope management group.
	ScopeManagementGroup *string `json:"scopeManagementGroup,omitempty" tf:"scope_management_group,omitempty"`

	// (String) Scope resource group.
	// Scope resource group.
	ScopeResourceGroup *string `json:"scopeResourceGroup,omitempty" tf:"scope_resource_group,omitempty"`

	// (String) Scope subscription.
	// Scope subscription ID.
	ScopeSubscription *string `json:"scopeSubscription,omitempty" tf:"scope_subscription,omitempty"`

	// (String) Scope tenant ID.
	// Scope tenant ID.
	ScopeTenant *string `json:"scopeTenant,omitempty" tf:"scope_tenant,omitempty"`

	// (String) Savings plan term. One of: ONE_YEAR, THREE_YEARS, FIVE_YEARS.
	// Savings plan term. One of: ONE_YEAR, THREE_YEARS, FIVE_YEARS.
	Term *string `json:"term,omitempty" tf:"term,omitempty"`
}

type AzureSavingsPlanDetailsObservation struct {

	// (Number) Commitment amount in USD per hour.
	// Hourly commitment amount in USD per hour.
	CommitmentAmount *float64 `json:"commitmentAmount,omitempty" tf:"commitment_amount,omitempty"`

	// (String) Commitment ID.
	// Savings plan ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Provisioning state (e.g. Succeeded, Expired, Cancelled).
	// Provisioning state (e.g. Succeeded, Expired, Cancelled).
	ProvisioningState *string `json:"provisioningState,omitempty" tf:"provisioning_state,omitempty"`

	// (String) Scope: whether the commitment applies to a region or an availability zone.
	// Applied scope type. One of: SINGLE, SHARED, MANAGEMENT_GROUP.
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// (String) Scope management group.
	// Scope management group.
	ScopeManagementGroup *string `json:"scopeManagementGroup,omitempty" tf:"scope_management_group,omitempty"`

	// (String) Scope resource group.
	// Scope resource group.
	ScopeResourceGroup *string `json:"scopeResourceGroup,omitempty" tf:"scope_resource_group,omitempty"`

	// (String) Scope subscription.
	// Scope subscription ID.
	ScopeSubscription *string `json:"scopeSubscription,omitempty" tf:"scope_subscription,omitempty"`

	// (String) Scope tenant ID.
	// Scope tenant ID.
	ScopeTenant *string `json:"scopeTenant,omitempty" tf:"scope_tenant,omitempty"`

	// (String) Savings plan term. One of: ONE_YEAR, THREE_YEARS, FIVE_YEARS.
	// Savings plan term. One of: ONE_YEAR, THREE_YEARS, FIVE_YEARS.
	Term *string `json:"term,omitempty" tf:"term,omitempty"`
}

type AzureSavingsPlanDetailsParameters struct {

	// (Number) Commitment amount in USD per hour.
	// Hourly commitment amount in USD per hour.
	// +kubebuilder:validation:Optional
	CommitmentAmount *float64 `json:"commitmentAmount,omitempty" tf:"commitment_amount,omitempty"`

	// (String) Commitment ID.
	// Savings plan ID.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// (String) Provisioning state (e.g. Succeeded, Expired, Cancelled).
	// Provisioning state (e.g. Succeeded, Expired, Cancelled).
	// +kubebuilder:validation:Optional
	ProvisioningState *string `json:"provisioningState,omitempty" tf:"provisioning_state,omitempty"`

	// (String) Scope: whether the commitment applies to a region or an availability zone.
	// Applied scope type. One of: SINGLE, SHARED, MANAGEMENT_GROUP.
	// +kubebuilder:validation:Optional
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// (String) Scope management group.
	// Scope management group.
	// +kubebuilder:validation:Optional
	ScopeManagementGroup *string `json:"scopeManagementGroup,omitempty" tf:"scope_management_group,omitempty"`

	// (String) Scope resource group.
	// Scope resource group.
	// +kubebuilder:validation:Optional
	ScopeResourceGroup *string `json:"scopeResourceGroup,omitempty" tf:"scope_resource_group,omitempty"`

	// (String) Scope subscription.
	// Scope subscription ID.
	// +kubebuilder:validation:Optional
	ScopeSubscription *string `json:"scopeSubscription,omitempty" tf:"scope_subscription,omitempty"`

	// (String) Scope tenant ID.
	// Scope tenant ID.
	// +kubebuilder:validation:Optional
	ScopeTenant *string `json:"scopeTenant,omitempty" tf:"scope_tenant,omitempty"`

	// (String) Savings plan term. One of: ONE_YEAR, THREE_YEARS, FIVE_YEARS.
	// Savings plan term. One of: ONE_YEAR, THREE_YEARS, FIVE_YEARS.
	// +kubebuilder:validation:Optional
	Term *string `json:"term,omitempty" tf:"term,omitempty"`
}

type CommitmentInitParameters struct {

	// 1.0). 1.0 means 100%. Defaults to 1.0.
	// Allowed usage of the commitment (0.0-1.0). 1.0 means 100%. Defaults to 1.0.
	AllowedUsage *float64 `json:"allowedUsage,omitempty" tf:"allowed_usage,omitempty"`

	// assign the commitment to all matching clusters in the commitment's region. If not set, the server's auto-assignment logic determines the value at creation time. Set to false to explicitly disable auto-assignment. Not supported for CAPACITY_BLOCK or targeted ON_DEMAND_CAPACITY_RESERVATION commitments.
	// Auto-assign the commitment to all matching clusters in the commitment's region. If not set, the server's auto-assignment logic determines the value at creation time. Set to false to explicitly disable auto-assignment. Not supported for CAPACITY_BLOCK or targeted ON_DEMAND_CAPACITY_RESERVATION commitments.
	AutoAssignment *bool `json:"autoAssignment,omitempty" tf:"auto_assignment,omitempty"`

	// (String) Controls whether the autoscaler can use this commitment. One of: ACTIVE, INACTIVE. Defaults to INACTIVE (matches the API default); set to ACTIVE for the autoscaler to use the commitment.
	// Controls whether the autoscaler can use this commitment. One of: ACTIVE, INACTIVE. Defaults to INACTIVE (matches the API default); set to ACTIVE for the autoscaler to use the commitment.
	AutoscalingStatus *string `json:"autoscalingStatus,omitempty" tf:"autoscaling_status,omitempty"`

	// (Attributes) AWS Capacity Block details. Required when type is CAPACITY_BLOCK. (see below for nested schema)
	// AWS Capacity Block details. Required when type is CAPACITY_BLOCK.
	AwsCapacityBlockDetails *AwsCapacityBlockDetailsInitParameters `json:"awsCapacityBlockDetails,omitempty" tf:"aws_capacity_block_details,omitempty"`

	// Demand Capacity Reservation details. Required when type is ON_DEMAND_CAPACITY_RESERVATION on AWS. (see below for nested schema)
	// AWS On-Demand Capacity Reservation details. Required when type is ON_DEMAND_CAPACITY_RESERVATION on AWS.
	AwsOdcrDetails *AwsOdcrDetailsInitParameters `json:"awsOdcrDetails,omitempty" tf:"aws_odcr_details,omitempty"`

	// (Attributes) AWS Reserved Instances details. Required when type is RESERVED_INSTANCE on AWS. (see below for nested schema)
	// AWS Reserved Instances details. Required when type is RESERVED_INSTANCE on AWS.
	AwsReservedInstancesDetails *AwsReservedInstancesDetailsInitParameters `json:"awsReservedInstancesDetails,omitempty" tf:"aws_reserved_instances_details,omitempty"`

	// (Attributes) AWS Savings Plan details. Required when type is SAVINGS_PLAN on AWS. (see below for nested schema)
	// AWS Savings Plan details. Required when type is SAVINGS_PLAN on AWS.
	AwsSavingsPlanDetails *AwsSavingsPlanDetailsInitParameters `json:"awsSavingsPlanDetails,omitempty" tf:"aws_savings_plan_details,omitempty"`

	// (Attributes) Azure Reservation details. Required when type is RESERVED_INSTANCE on Azure. (see below for nested schema)
	// Azure Reservation details. Required when type is RESERVED_INSTANCE on Azure.
	AzureReservationDetails *AzureReservationDetailsInitParameters `json:"azureReservationDetails,omitempty" tf:"azure_reservation_details,omitempty"`

	// (Attributes) Azure Savings Plan details. Required when type is SAVINGS_PLAN on Azure. (see below for nested schema)
	// Azure Savings Plan details. Required when type is SAVINGS_PLAN on Azure.
	AzureSavingsPlanDetails *AzureSavingsPlanDetailsInitParameters `json:"azureSavingsPlanDetails,omitempty" tf:"azure_savings_plan_details,omitempty"`

	// (String) Cloud provider. One of: AWS, GCP, AZURE.
	// Cloud provider. One of: AWS, GCP, AZURE.
	Cloud *string `json:"cloud,omitempty" tf:"cloud,omitempty"`

	// (String) End time of the commitment (RFC3339).
	// End time of the commitment (RFC3339).
	EndTime *string `json:"endTime,omitempty" tf:"end_time,omitempty"`

	// (Attributes) GCP capacity reservation details. Required when type is ON_DEMAND_CAPACITY_RESERVATION on GCP. (see below for nested schema)
	// GCP capacity reservation details. Required when type is ON_DEMAND_CAPACITY_RESERVATION on GCP.
	GCPCapacityReservationDetails *GCPCapacityReservationDetailsInitParameters `json:"gcpCapacityReservationDetails,omitempty" tf:"gcp_capacity_reservation_details,omitempty"`

	// (Attributes) GCP Flex CUD details. Required when type is FLEX_CUD. (see below for nested schema)
	// GCP Flex CUD details. Required when type is FLEX_CUD.
	GCPFlexCudDetails *GCPFlexCudDetailsInitParameters `json:"gcpFlexCudDetails,omitempty" tf:"gcp_flex_cud_details,omitempty"`

	// (Attributes) GCP Resource CUD details. Required when type is RESOURCE_CUD. (see below for nested schema)
	// GCP Resource CUD details. Required when type is RESOURCE_CUD.
	GCPResourceCudDetails *GCPResourceCudDetailsInitParameters `json:"gcpResourceCudDetails,omitempty" tf:"gcp_resource_cud_details,omitempty"`

	// (String) Commitment name.
	// Commitment name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) CAST AI organization ID. If not provided, the organization from the provider configuration is used.
	// CAST AI organization ID. If not provided, the organization from the provider configuration is used.
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// priority clusters are ignored.
	// If enabled, resources used by lower-priority clusters are ignored.
	Prioritization *bool `json:"prioritization,omitempty" tf:"prioritization,omitempty"`

	// (String) Region where the commitment is applicable.
	// Region where the commitment is applicable.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) Scaling strategy for the autoscaler. One of: DEFAULT, CPU_BASED, MEMORY_BASED.
	// Scaling strategy for the autoscaler. One of: DEFAULT, CPU_BASED, MEMORY_BASED.
	ScalingStrategy *string `json:"scalingStrategy,omitempty" tf:"scaling_strategy,omitempty"`

	// 01-01T00:00:00Z).
	// Start time of the commitment (RFC3339, e.g. 2026-01-01T00:00:00Z).
	StartTime *string `json:"startTime,omitempty" tf:"start_time,omitempty"`

	// (String) Commitment type. One of: RESERVED_INSTANCE, RESOURCE_CUD, SAVINGS_PLAN, CAPACITY_BLOCK, ON_DEMAND_CAPACITY_RESERVATION, FLEX_CUD. The matching details block must be set.
	// Commitment type. One of: RESERVED_INSTANCE, RESOURCE_CUD, SAVINGS_PLAN, CAPACITY_BLOCK, ON_DEMAND_CAPACITY_RESERVATION, FLEX_CUD. The matching details block must be set.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type CommitmentObservation struct {

	// 1.0). 1.0 means 100%. Defaults to 1.0.
	// Allowed usage of the commitment (0.0-1.0). 1.0 means 100%. Defaults to 1.0.
	AllowedUsage *float64 `json:"allowedUsage,omitempty" tf:"allowed_usage,omitempty"`

	// assign the commitment to all matching clusters in the commitment's region. If not set, the server's auto-assignment logic determines the value at creation time. Set to false to explicitly disable auto-assignment. Not supported for CAPACITY_BLOCK or targeted ON_DEMAND_CAPACITY_RESERVATION commitments.
	// Auto-assign the commitment to all matching clusters in the commitment's region. If not set, the server's auto-assignment logic determines the value at creation time. Set to false to explicitly disable auto-assignment. Not supported for CAPACITY_BLOCK or targeted ON_DEMAND_CAPACITY_RESERVATION commitments.
	AutoAssignment *bool `json:"autoAssignment,omitempty" tf:"auto_assignment,omitempty"`

	// (String) Controls whether the autoscaler can use this commitment. One of: ACTIVE, INACTIVE. Defaults to INACTIVE (matches the API default); set to ACTIVE for the autoscaler to use the commitment.
	// Controls whether the autoscaler can use this commitment. One of: ACTIVE, INACTIVE. Defaults to INACTIVE (matches the API default); set to ACTIVE for the autoscaler to use the commitment.
	AutoscalingStatus *string `json:"autoscalingStatus,omitempty" tf:"autoscaling_status,omitempty"`

	// (Attributes) AWS Capacity Block details. Required when type is CAPACITY_BLOCK. (see below for nested schema)
	// AWS Capacity Block details. Required when type is CAPACITY_BLOCK.
	AwsCapacityBlockDetails *AwsCapacityBlockDetailsObservation `json:"awsCapacityBlockDetails,omitempty" tf:"aws_capacity_block_details,omitempty"`

	// Demand Capacity Reservation details. Required when type is ON_DEMAND_CAPACITY_RESERVATION on AWS. (see below for nested schema)
	// AWS On-Demand Capacity Reservation details. Required when type is ON_DEMAND_CAPACITY_RESERVATION on AWS.
	AwsOdcrDetails *AwsOdcrDetailsObservation `json:"awsOdcrDetails,omitempty" tf:"aws_odcr_details,omitempty"`

	// (Attributes) AWS Reserved Instances details. Required when type is RESERVED_INSTANCE on AWS. (see below for nested schema)
	// AWS Reserved Instances details. Required when type is RESERVED_INSTANCE on AWS.
	AwsReservedInstancesDetails *AwsReservedInstancesDetailsObservation `json:"awsReservedInstancesDetails,omitempty" tf:"aws_reserved_instances_details,omitempty"`

	// (Attributes) AWS Savings Plan details. Required when type is SAVINGS_PLAN on AWS. (see below for nested schema)
	// AWS Savings Plan details. Required when type is SAVINGS_PLAN on AWS.
	AwsSavingsPlanDetails *AwsSavingsPlanDetailsObservation `json:"awsSavingsPlanDetails,omitempty" tf:"aws_savings_plan_details,omitempty"`

	// (Attributes) Azure Reservation details. Required when type is RESERVED_INSTANCE on Azure. (see below for nested schema)
	// Azure Reservation details. Required when type is RESERVED_INSTANCE on Azure.
	AzureReservationDetails *AzureReservationDetailsObservation `json:"azureReservationDetails,omitempty" tf:"azure_reservation_details,omitempty"`

	// (Attributes) Azure Savings Plan details. Required when type is SAVINGS_PLAN on Azure. (see below for nested schema)
	// Azure Savings Plan details. Required when type is SAVINGS_PLAN on Azure.
	AzureSavingsPlanDetails *AzureSavingsPlanDetailsObservation `json:"azureSavingsPlanDetails,omitempty" tf:"azure_savings_plan_details,omitempty"`

	// (String) Cloud provider. One of: AWS, GCP, AZURE.
	// Cloud provider. One of: AWS, GCP, AZURE.
	Cloud *string `json:"cloud,omitempty" tf:"cloud,omitempty"`

	// (String) Creation time.
	// Creation time.
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	// (String) End time of the commitment (RFC3339).
	// End time of the commitment (RFC3339).
	EndTime *string `json:"endTime,omitempty" tf:"end_time,omitempty"`

	// (Attributes) GCP capacity reservation details. Required when type is ON_DEMAND_CAPACITY_RESERVATION on GCP. (see below for nested schema)
	// GCP capacity reservation details. Required when type is ON_DEMAND_CAPACITY_RESERVATION on GCP.
	GCPCapacityReservationDetails *GCPCapacityReservationDetailsObservation `json:"gcpCapacityReservationDetails,omitempty" tf:"gcp_capacity_reservation_details,omitempty"`

	// (Attributes) GCP Flex CUD details. Required when type is FLEX_CUD. (see below for nested schema)
	// GCP Flex CUD details. Required when type is FLEX_CUD.
	GCPFlexCudDetails *GCPFlexCudDetailsObservation `json:"gcpFlexCudDetails,omitempty" tf:"gcp_flex_cud_details,omitempty"`

	// (Attributes) GCP Resource CUD details. Required when type is RESOURCE_CUD. (see below for nested schema)
	// GCP Resource CUD details. Required when type is RESOURCE_CUD.
	GCPResourceCudDetails *GCPResourceCudDetailsObservation `json:"gcpResourceCudDetails,omitempty" tf:"gcp_resource_cud_details,omitempty"`

	// (String) Commitment ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Commitment name.
	// Commitment name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) CAST AI organization ID. If not provided, the organization from the provider configuration is used.
	// CAST AI organization ID. If not provided, the organization from the provider configuration is used.
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// priority clusters are ignored.
	// If enabled, resources used by lower-priority clusters are ignored.
	Prioritization *bool `json:"prioritization,omitempty" tf:"prioritization,omitempty"`

	// (String) Region where the commitment is applicable.
	// Region where the commitment is applicable.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) Scaling strategy for the autoscaler. One of: DEFAULT, CPU_BASED, MEMORY_BASED.
	// Scaling strategy for the autoscaler. One of: DEFAULT, CPU_BASED, MEMORY_BASED.
	ScalingStrategy *string `json:"scalingStrategy,omitempty" tf:"scaling_strategy,omitempty"`

	// 01-01T00:00:00Z).
	// Start time of the commitment (RFC3339, e.g. 2026-01-01T00:00:00Z).
	StartTime *string `json:"startTime,omitempty" tf:"start_time,omitempty"`

	// (String) Computed lifecycle state of the commitment.
	// Computed lifecycle state of the commitment.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (String) Commitment type. One of: RESERVED_INSTANCE, RESOURCE_CUD, SAVINGS_PLAN, CAPACITY_BLOCK, ON_DEMAND_CAPACITY_RESERVATION, FLEX_CUD. The matching details block must be set.
	// Commitment type. One of: RESERVED_INSTANCE, RESOURCE_CUD, SAVINGS_PLAN, CAPACITY_BLOCK, ON_DEMAND_CAPACITY_RESERVATION, FLEX_CUD. The matching details block must be set.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) Last update time.
	// Last update time.
	UpdateTime *string `json:"updateTime,omitempty" tf:"update_time,omitempty"`
}

type CommitmentParameters struct {

	// 1.0). 1.0 means 100%. Defaults to 1.0.
	// Allowed usage of the commitment (0.0-1.0). 1.0 means 100%. Defaults to 1.0.
	// +kubebuilder:validation:Optional
	AllowedUsage *float64 `json:"allowedUsage,omitempty" tf:"allowed_usage,omitempty"`

	// assign the commitment to all matching clusters in the commitment's region. If not set, the server's auto-assignment logic determines the value at creation time. Set to false to explicitly disable auto-assignment. Not supported for CAPACITY_BLOCK or targeted ON_DEMAND_CAPACITY_RESERVATION commitments.
	// Auto-assign the commitment to all matching clusters in the commitment's region. If not set, the server's auto-assignment logic determines the value at creation time. Set to false to explicitly disable auto-assignment. Not supported for CAPACITY_BLOCK or targeted ON_DEMAND_CAPACITY_RESERVATION commitments.
	// +kubebuilder:validation:Optional
	AutoAssignment *bool `json:"autoAssignment,omitempty" tf:"auto_assignment,omitempty"`

	// (String) Controls whether the autoscaler can use this commitment. One of: ACTIVE, INACTIVE. Defaults to INACTIVE (matches the API default); set to ACTIVE for the autoscaler to use the commitment.
	// Controls whether the autoscaler can use this commitment. One of: ACTIVE, INACTIVE. Defaults to INACTIVE (matches the API default); set to ACTIVE for the autoscaler to use the commitment.
	// +kubebuilder:validation:Optional
	AutoscalingStatus *string `json:"autoscalingStatus,omitempty" tf:"autoscaling_status,omitempty"`

	// (Attributes) AWS Capacity Block details. Required when type is CAPACITY_BLOCK. (see below for nested schema)
	// AWS Capacity Block details. Required when type is CAPACITY_BLOCK.
	// +kubebuilder:validation:Optional
	AwsCapacityBlockDetails *AwsCapacityBlockDetailsParameters `json:"awsCapacityBlockDetails,omitempty" tf:"aws_capacity_block_details,omitempty"`

	// Demand Capacity Reservation details. Required when type is ON_DEMAND_CAPACITY_RESERVATION on AWS. (see below for nested schema)
	// AWS On-Demand Capacity Reservation details. Required when type is ON_DEMAND_CAPACITY_RESERVATION on AWS.
	// +kubebuilder:validation:Optional
	AwsOdcrDetails *AwsOdcrDetailsParameters `json:"awsOdcrDetails,omitempty" tf:"aws_odcr_details,omitempty"`

	// (Attributes) AWS Reserved Instances details. Required when type is RESERVED_INSTANCE on AWS. (see below for nested schema)
	// AWS Reserved Instances details. Required when type is RESERVED_INSTANCE on AWS.
	// +kubebuilder:validation:Optional
	AwsReservedInstancesDetails *AwsReservedInstancesDetailsParameters `json:"awsReservedInstancesDetails,omitempty" tf:"aws_reserved_instances_details,omitempty"`

	// (Attributes) AWS Savings Plan details. Required when type is SAVINGS_PLAN on AWS. (see below for nested schema)
	// AWS Savings Plan details. Required when type is SAVINGS_PLAN on AWS.
	// +kubebuilder:validation:Optional
	AwsSavingsPlanDetails *AwsSavingsPlanDetailsParameters `json:"awsSavingsPlanDetails,omitempty" tf:"aws_savings_plan_details,omitempty"`

	// (Attributes) Azure Reservation details. Required when type is RESERVED_INSTANCE on Azure. (see below for nested schema)
	// Azure Reservation details. Required when type is RESERVED_INSTANCE on Azure.
	// +kubebuilder:validation:Optional
	AzureReservationDetails *AzureReservationDetailsParameters `json:"azureReservationDetails,omitempty" tf:"azure_reservation_details,omitempty"`

	// (Attributes) Azure Savings Plan details. Required when type is SAVINGS_PLAN on Azure. (see below for nested schema)
	// Azure Savings Plan details. Required when type is SAVINGS_PLAN on Azure.
	// +kubebuilder:validation:Optional
	AzureSavingsPlanDetails *AzureSavingsPlanDetailsParameters `json:"azureSavingsPlanDetails,omitempty" tf:"azure_savings_plan_details,omitempty"`

	// (String) Cloud provider. One of: AWS, GCP, AZURE.
	// Cloud provider. One of: AWS, GCP, AZURE.
	// +kubebuilder:validation:Optional
	Cloud *string `json:"cloud,omitempty" tf:"cloud,omitempty"`

	// (String) End time of the commitment (RFC3339).
	// End time of the commitment (RFC3339).
	// +kubebuilder:validation:Optional
	EndTime *string `json:"endTime,omitempty" tf:"end_time,omitempty"`

	// (Attributes) GCP capacity reservation details. Required when type is ON_DEMAND_CAPACITY_RESERVATION on GCP. (see below for nested schema)
	// GCP capacity reservation details. Required when type is ON_DEMAND_CAPACITY_RESERVATION on GCP.
	// +kubebuilder:validation:Optional
	GCPCapacityReservationDetails *GCPCapacityReservationDetailsParameters `json:"gcpCapacityReservationDetails,omitempty" tf:"gcp_capacity_reservation_details,omitempty"`

	// (Attributes) GCP Flex CUD details. Required when type is FLEX_CUD. (see below for nested schema)
	// GCP Flex CUD details. Required when type is FLEX_CUD.
	// +kubebuilder:validation:Optional
	GCPFlexCudDetails *GCPFlexCudDetailsParameters `json:"gcpFlexCudDetails,omitempty" tf:"gcp_flex_cud_details,omitempty"`

	// (Attributes) GCP Resource CUD details. Required when type is RESOURCE_CUD. (see below for nested schema)
	// GCP Resource CUD details. Required when type is RESOURCE_CUD.
	// +kubebuilder:validation:Optional
	GCPResourceCudDetails *GCPResourceCudDetailsParameters `json:"gcpResourceCudDetails,omitempty" tf:"gcp_resource_cud_details,omitempty"`

	// (String) Commitment name.
	// Commitment name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) CAST AI organization ID. If not provided, the organization from the provider configuration is used.
	// CAST AI organization ID. If not provided, the organization from the provider configuration is used.
	// +kubebuilder:validation:Optional
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// priority clusters are ignored.
	// If enabled, resources used by lower-priority clusters are ignored.
	// +kubebuilder:validation:Optional
	Prioritization *bool `json:"prioritization,omitempty" tf:"prioritization,omitempty"`

	// (String) Region where the commitment is applicable.
	// Region where the commitment is applicable.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) Scaling strategy for the autoscaler. One of: DEFAULT, CPU_BASED, MEMORY_BASED.
	// Scaling strategy for the autoscaler. One of: DEFAULT, CPU_BASED, MEMORY_BASED.
	// +kubebuilder:validation:Optional
	ScalingStrategy *string `json:"scalingStrategy,omitempty" tf:"scaling_strategy,omitempty"`

	// 01-01T00:00:00Z).
	// Start time of the commitment (RFC3339, e.g. 2026-01-01T00:00:00Z).
	// +kubebuilder:validation:Optional
	StartTime *string `json:"startTime,omitempty" tf:"start_time,omitempty"`

	// (String) Commitment type. One of: RESERVED_INSTANCE, RESOURCE_CUD, SAVINGS_PLAN, CAPACITY_BLOCK, ON_DEMAND_CAPACITY_RESERVATION, FLEX_CUD. The matching details block must be set.
	// Commitment type. One of: RESERVED_INSTANCE, RESOURCE_CUD, SAVINGS_PLAN, CAPACITY_BLOCK, ON_DEMAND_CAPACITY_RESERVATION, FLEX_CUD. The matching details block must be set.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type GCPCapacityReservationDetailsInitParameters struct {

	// (Attributes List) Accelerators (GPUs) reserved VMs must match exactly. (see below for nested schema)
	// Accelerators (GPUs) reserved VMs must match exactly.
	Accelerators []AcceleratorsInitParameters `json:"accelerators,omitempty" tf:"accelerators,omitempty"`

	// (Number) Assured count for the reservation.
	// Assured count for the reservation.
	AssuredInstanceCount *float64 `json:"assuredInstanceCount,omitempty" tf:"assured_instance_count,omitempty"`

	// (String) Commitment ID.
	// Reservation ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Number) Number of instances currently in use.
	// Number of instances currently in use.
	InUseInstanceCount *float64 `json:"inUseInstanceCount,omitempty" tf:"in_use_instance_count,omitempty"`

	// (String) EC2 instance type.
	// Instance type covered by the reservation.
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// (Attributes List) Local SSD disks reserved VMs must match exactly. (see below for nested schema)
	// Local SSD disks reserved VMs must match exactly.
	LocalSsds []LocalSsdsInitParameters `json:"localSsds,omitempty" tf:"local_ssds,omitempty"`

	// (String) Minimum CPU platform the reserved VMs require (e.g. Intel Cascade Lake).
	// Minimum CPU platform the reserved VMs require (e.g. Intel Cascade Lake).
	MinCPUPlatform *string `json:"minCpuPlatform,omitempty" tf:"min_cpu_platform,omitempty"`

	// (String) GCP project ID that owns the reservation.
	// GCP project ID that owns the reservation.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// defined URL for the reservation (e.g. https://www.googleapis.com/compute/v1/projects/my-project/zones/us-central1-a/reservations/my-reservation).
	// Server-defined URL for the reservation (e.g. https://www.googleapis.com/compute/v1/projects/my-project/zones/us-central1-a/reservations/my-reservation).
	SelfLink *string `json:"selfLink,omitempty" tf:"self_link,omitempty"`

	// (Attributes) Reservation sharing settings. (see below for nested schema)
	// Reservation sharing settings.
	ShareSettings []ShareSettingsInitParameters `json:"shareSettings,omitempty" tf:"share_settings,omitempty"`

	// (Boolean) Whether the reservation requires specific reservation affinity.
	// Whether the reservation requires specific reservation affinity.
	SpecificReservationRequired *bool `json:"specificReservationRequired,omitempty" tf:"specific_reservation_required,omitempty"`

	// (String) Computed lifecycle state of the commitment.
	// Runtime state of the reservation (e.g. READY).
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (Number) Total reserved instance count.
	// Total number of instances reserved.
	TotalInstanceCount *float64 `json:"totalInstanceCount,omitempty" tf:"total_instance_count,omitempty"`

	// (String) GCP zone of the reservation.
	// GCP zone of the reservation.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type GCPCapacityReservationDetailsObservation struct {

	// (Attributes List) Accelerators (GPUs) reserved VMs must match exactly. (see below for nested schema)
	// Accelerators (GPUs) reserved VMs must match exactly.
	Accelerators []AcceleratorsObservation `json:"accelerators,omitempty" tf:"accelerators,omitempty"`

	// (Number) Assured count for the reservation.
	// Assured count for the reservation.
	AssuredInstanceCount *float64 `json:"assuredInstanceCount,omitempty" tf:"assured_instance_count,omitempty"`

	// (String) Commitment ID.
	// Reservation ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Number) Number of instances currently in use.
	// Number of instances currently in use.
	InUseInstanceCount *float64 `json:"inUseInstanceCount,omitempty" tf:"in_use_instance_count,omitempty"`

	// (String) EC2 instance type.
	// Instance type covered by the reservation.
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// (Attributes List) Local SSD disks reserved VMs must match exactly. (see below for nested schema)
	// Local SSD disks reserved VMs must match exactly.
	LocalSsds []LocalSsdsObservation `json:"localSsds,omitempty" tf:"local_ssds,omitempty"`

	// (String) Minimum CPU platform the reserved VMs require (e.g. Intel Cascade Lake).
	// Minimum CPU platform the reserved VMs require (e.g. Intel Cascade Lake).
	MinCPUPlatform *string `json:"minCpuPlatform,omitempty" tf:"min_cpu_platform,omitempty"`

	// (String) GCP project ID that owns the reservation.
	// GCP project ID that owns the reservation.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// defined URL for the reservation (e.g. https://www.googleapis.com/compute/v1/projects/my-project/zones/us-central1-a/reservations/my-reservation).
	// Server-defined URL for the reservation (e.g. https://www.googleapis.com/compute/v1/projects/my-project/zones/us-central1-a/reservations/my-reservation).
	SelfLink *string `json:"selfLink,omitempty" tf:"self_link,omitempty"`

	// (Attributes) Reservation sharing settings. (see below for nested schema)
	// Reservation sharing settings.
	ShareSettings []ShareSettingsObservation `json:"shareSettings,omitempty" tf:"share_settings,omitempty"`

	// (Boolean) Whether the reservation requires specific reservation affinity.
	// Whether the reservation requires specific reservation affinity.
	SpecificReservationRequired *bool `json:"specificReservationRequired,omitempty" tf:"specific_reservation_required,omitempty"`

	// (String) Computed lifecycle state of the commitment.
	// Runtime state of the reservation (e.g. READY).
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (Number) Total reserved instance count.
	// Total number of instances reserved.
	TotalInstanceCount *float64 `json:"totalInstanceCount,omitempty" tf:"total_instance_count,omitempty"`

	// (String) GCP zone of the reservation.
	// GCP zone of the reservation.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type GCPCapacityReservationDetailsParameters struct {

	// (Attributes List) Accelerators (GPUs) reserved VMs must match exactly. (see below for nested schema)
	// Accelerators (GPUs) reserved VMs must match exactly.
	// +kubebuilder:validation:Optional
	Accelerators []AcceleratorsParameters `json:"accelerators,omitempty" tf:"accelerators,omitempty"`

	// (Number) Assured count for the reservation.
	// Assured count for the reservation.
	// +kubebuilder:validation:Optional
	AssuredInstanceCount *float64 `json:"assuredInstanceCount,omitempty" tf:"assured_instance_count,omitempty"`

	// (String) Commitment ID.
	// Reservation ID.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// (Number) Number of instances currently in use.
	// Number of instances currently in use.
	// +kubebuilder:validation:Optional
	InUseInstanceCount *float64 `json:"inUseInstanceCount,omitempty" tf:"in_use_instance_count,omitempty"`

	// (String) EC2 instance type.
	// Instance type covered by the reservation.
	// +kubebuilder:validation:Optional
	InstanceType *string `json:"instanceType" tf:"instance_type,omitempty"`

	// (Attributes List) Local SSD disks reserved VMs must match exactly. (see below for nested schema)
	// Local SSD disks reserved VMs must match exactly.
	// +kubebuilder:validation:Optional
	LocalSsds []LocalSsdsParameters `json:"localSsds,omitempty" tf:"local_ssds,omitempty"`

	// (String) Minimum CPU platform the reserved VMs require (e.g. Intel Cascade Lake).
	// Minimum CPU platform the reserved VMs require (e.g. Intel Cascade Lake).
	// +kubebuilder:validation:Optional
	MinCPUPlatform *string `json:"minCpuPlatform,omitempty" tf:"min_cpu_platform,omitempty"`

	// (String) GCP project ID that owns the reservation.
	// GCP project ID that owns the reservation.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// defined URL for the reservation (e.g. https://www.googleapis.com/compute/v1/projects/my-project/zones/us-central1-a/reservations/my-reservation).
	// Server-defined URL for the reservation (e.g. https://www.googleapis.com/compute/v1/projects/my-project/zones/us-central1-a/reservations/my-reservation).
	// +kubebuilder:validation:Optional
	SelfLink *string `json:"selfLink,omitempty" tf:"self_link,omitempty"`

	// (Attributes) Reservation sharing settings. (see below for nested schema)
	// Reservation sharing settings.
	// +kubebuilder:validation:Optional
	ShareSettings []ShareSettingsParameters `json:"shareSettings,omitempty" tf:"share_settings,omitempty"`

	// (Boolean) Whether the reservation requires specific reservation affinity.
	// Whether the reservation requires specific reservation affinity.
	// +kubebuilder:validation:Optional
	SpecificReservationRequired *bool `json:"specificReservationRequired,omitempty" tf:"specific_reservation_required,omitempty"`

	// (String) Computed lifecycle state of the commitment.
	// Runtime state of the reservation (e.g. READY).
	// +kubebuilder:validation:Optional
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (Number) Total reserved instance count.
	// Total number of instances reserved.
	// +kubebuilder:validation:Optional
	TotalInstanceCount *float64 `json:"totalInstanceCount" tf:"total_instance_count,omitempty"`

	// (String) GCP zone of the reservation.
	// GCP zone of the reservation.
	// +kubebuilder:validation:Optional
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type GCPFlexCudDetailsInitParameters struct {

	// (Number) Commitment amount in USD per hour.
	// Hourly commitment in USD per hour.
	CommitmentAmount *float64 `json:"commitmentAmount,omitempty" tf:"commitment_amount,omitempty"`

	// specified display name.
	// User-specified display name.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (String) Line item ID within the order.
	// Line item ID within the order.
	LineItemID *string `json:"lineItemId,omitempty" tf:"line_item_id,omitempty"`

	// (String) Offer identifier.
	// Offer identifier.
	Offer *string `json:"offer,omitempty" tf:"offer,omitempty"`

	// (String) Resource name of the order.
	// Resource name of the order.
	OrderName *string `json:"orderName,omitempty" tf:"order_name,omitempty"`

	// (String) Reservation term plan. One of: ONE_YEAR, THREE_YEAR.
	// CUD plan. One of: TWELVE_MONTH, THIRTY_SIX_MONTH.
	Plan *string `json:"plan,omitempty" tf:"plan,omitempty"`

	// (String) Region where the commitment is applicable.
	// Region (can be empty for global Flex CUDs).
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) Computed lifecycle state of the commitment.
	// State (ACTIVE, CANCELED).
	State *string `json:"state,omitempty" tf:"state,omitempty"`
}

type GCPFlexCudDetailsObservation struct {

	// (Number) Commitment amount in USD per hour.
	// Hourly commitment in USD per hour.
	CommitmentAmount *float64 `json:"commitmentAmount,omitempty" tf:"commitment_amount,omitempty"`

	// specified display name.
	// User-specified display name.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (String) Line item ID within the order.
	// Line item ID within the order.
	LineItemID *string `json:"lineItemId,omitempty" tf:"line_item_id,omitempty"`

	// (String) Offer identifier.
	// Offer identifier.
	Offer *string `json:"offer,omitempty" tf:"offer,omitempty"`

	// (String) Resource name of the order.
	// Resource name of the order.
	OrderName *string `json:"orderName,omitempty" tf:"order_name,omitempty"`

	// (String) Reservation term plan. One of: ONE_YEAR, THREE_YEAR.
	// CUD plan. One of: TWELVE_MONTH, THIRTY_SIX_MONTH.
	Plan *string `json:"plan,omitempty" tf:"plan,omitempty"`

	// (String) Region where the commitment is applicable.
	// Region (can be empty for global Flex CUDs).
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) Computed lifecycle state of the commitment.
	// State (ACTIVE, CANCELED).
	State *string `json:"state,omitempty" tf:"state,omitempty"`
}

type GCPFlexCudDetailsParameters struct {

	// (Number) Commitment amount in USD per hour.
	// Hourly commitment in USD per hour.
	// +kubebuilder:validation:Optional
	CommitmentAmount *float64 `json:"commitmentAmount,omitempty" tf:"commitment_amount,omitempty"`

	// specified display name.
	// User-specified display name.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (String) Line item ID within the order.
	// Line item ID within the order.
	// +kubebuilder:validation:Optional
	LineItemID *string `json:"lineItemId" tf:"line_item_id,omitempty"`

	// (String) Offer identifier.
	// Offer identifier.
	// +kubebuilder:validation:Optional
	Offer *string `json:"offer,omitempty" tf:"offer,omitempty"`

	// (String) Resource name of the order.
	// Resource name of the order.
	// +kubebuilder:validation:Optional
	OrderName *string `json:"orderName,omitempty" tf:"order_name,omitempty"`

	// (String) Reservation term plan. One of: ONE_YEAR, THREE_YEAR.
	// CUD plan. One of: TWELVE_MONTH, THIRTY_SIX_MONTH.
	// +kubebuilder:validation:Optional
	Plan *string `json:"plan,omitempty" tf:"plan,omitempty"`

	// (String) Region where the commitment is applicable.
	// Region (can be empty for global Flex CUDs).
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) Computed lifecycle state of the commitment.
	// State (ACTIVE, CANCELED).
	// +kubebuilder:validation:Optional
	State *string `json:"state,omitempty" tf:"state,omitempty"`
}

type GCPResourceCudDetailsInitParameters struct {

	// (Number) Committed CPU count.
	// Committed CPU count.
	CPU *float64 `json:"cpu,omitempty" tf:"cpu,omitempty"`

	// (String) CUD ID from GCP.
	// CUD ID from GCP.
	CudID *string `json:"cudId,omitempty" tf:"cud_id,omitempty"`

	// (Number) Committed memory in MB.
	// Committed memory in MB.
	MemoryMb *float64 `json:"memoryMb,omitempty" tf:"memory_mb,omitempty"`

	// (String) Reservation term plan. One of: ONE_YEAR, THREE_YEAR.
	// CUD plan. One of: TWELVE_MONTH, THIRTY_SIX_MONTH.
	Plan *string `json:"plan,omitempty" tf:"plan,omitempty"`

	// (String) Provisioning state (e.g. Succeeded).
	// Commitment status (e.g. ACTIVE).
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String) Commitment type. One of: RESERVED_INSTANCE, RESOURCE_CUD, SAVINGS_PLAN, CAPACITY_BLOCK, ON_DEMAND_CAPACITY_RESERVATION, FLEX_CUD. The matching details block must be set.
	// GCP commitment type (e.g. COMPUTE_OPTIMIZED_C2D).
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type GCPResourceCudDetailsObservation struct {

	// (Number) Committed CPU count.
	// Committed CPU count.
	CPU *float64 `json:"cpu,omitempty" tf:"cpu,omitempty"`

	// (String) CUD ID from GCP.
	// CUD ID from GCP.
	CudID *string `json:"cudId,omitempty" tf:"cud_id,omitempty"`

	// (Number) Committed memory in MB.
	// Committed memory in MB.
	MemoryMb *float64 `json:"memoryMb,omitempty" tf:"memory_mb,omitempty"`

	// (String) Reservation term plan. One of: ONE_YEAR, THREE_YEAR.
	// CUD plan. One of: TWELVE_MONTH, THIRTY_SIX_MONTH.
	Plan *string `json:"plan,omitempty" tf:"plan,omitempty"`

	// (String) Provisioning state (e.g. Succeeded).
	// Commitment status (e.g. ACTIVE).
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String) Commitment type. One of: RESERVED_INSTANCE, RESOURCE_CUD, SAVINGS_PLAN, CAPACITY_BLOCK, ON_DEMAND_CAPACITY_RESERVATION, FLEX_CUD. The matching details block must be set.
	// GCP commitment type (e.g. COMPUTE_OPTIMIZED_C2D).
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type GCPResourceCudDetailsParameters struct {

	// (Number) Committed CPU count.
	// Committed CPU count.
	// +kubebuilder:validation:Optional
	CPU *float64 `json:"cpu,omitempty" tf:"cpu,omitempty"`

	// (String) CUD ID from GCP.
	// CUD ID from GCP.
	// +kubebuilder:validation:Optional
	CudID *string `json:"cudId" tf:"cud_id,omitempty"`

	// (Number) Committed memory in MB.
	// Committed memory in MB.
	// +kubebuilder:validation:Optional
	MemoryMb *float64 `json:"memoryMb,omitempty" tf:"memory_mb,omitempty"`

	// (String) Reservation term plan. One of: ONE_YEAR, THREE_YEAR.
	// CUD plan. One of: TWELVE_MONTH, THIRTY_SIX_MONTH.
	// +kubebuilder:validation:Optional
	Plan *string `json:"plan,omitempty" tf:"plan,omitempty"`

	// (String) Provisioning state (e.g. Succeeded).
	// Commitment status (e.g. ACTIVE).
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String) Commitment type. One of: RESERVED_INSTANCE, RESOURCE_CUD, SAVINGS_PLAN, CAPACITY_BLOCK, ON_DEMAND_CAPACITY_RESERVATION, FLEX_CUD. The matching details block must be set.
	// GCP commitment type (e.g. COMPUTE_OPTIMIZED_C2D).
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type LocalSsdsInitParameters struct {

	// (Number) Disk size in GB.
	// Disk size in GB.
	DiskSizeGb *float64 `json:"diskSizeGb,omitempty" tf:"disk_size_gb,omitempty"`

	// (String) Disk interface. One of: GCP_RESERVATION_LOCAL_SSD_INTERFACE_SCSI, GCP_RESERVATION_LOCAL_SSD_INTERFACE_NVME.
	// Disk interface. One of: GCP_RESERVATION_LOCAL_SSD_INTERFACE_SCSI, GCP_RESERVATION_LOCAL_SSD_INTERFACE_NVME.
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`
}

type LocalSsdsObservation struct {

	// (Number) Disk size in GB.
	// Disk size in GB.
	DiskSizeGb *float64 `json:"diskSizeGb,omitempty" tf:"disk_size_gb,omitempty"`

	// (String) Disk interface. One of: GCP_RESERVATION_LOCAL_SSD_INTERFACE_SCSI, GCP_RESERVATION_LOCAL_SSD_INTERFACE_NVME.
	// Disk interface. One of: GCP_RESERVATION_LOCAL_SSD_INTERFACE_SCSI, GCP_RESERVATION_LOCAL_SSD_INTERFACE_NVME.
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`
}

type LocalSsdsParameters struct {

	// (Number) Disk size in GB.
	// Disk size in GB.
	// +kubebuilder:validation:Optional
	DiskSizeGb *float64 `json:"diskSizeGb" tf:"disk_size_gb,omitempty"`

	// (String) Disk interface. One of: GCP_RESERVATION_LOCAL_SSD_INTERFACE_SCSI, GCP_RESERVATION_LOCAL_SSD_INTERFACE_NVME.
	// Disk interface. One of: GCP_RESERVATION_LOCAL_SSD_INTERFACE_SCSI, GCP_RESERVATION_LOCAL_SSD_INTERFACE_NVME.
	// +kubebuilder:validation:Optional
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`
}

type ShareSettingsInitParameters struct {

	// (List of String) Project IDs this reservation is shared with (SPECIFIC_PROJECTS share type only).
	// Project IDs this reservation is shared with (SPECIFIC_PROJECTS share type only).
	ProjectIds []*string `json:"projectIds,omitempty" tf:"project_ids,omitempty"`

	// (String) Share type. One of: GCP_RESERVATION_SHARE_TYPE_LOCAL, GCP_RESERVATION_SHARE_TYPE_SPECIFIC_PROJECTS, GCP_RESERVATION_SHARE_TYPE_ORGANIZATION.
	// Share type. One of: GCP_RESERVATION_SHARE_TYPE_LOCAL, GCP_RESERVATION_SHARE_TYPE_SPECIFIC_PROJECTS, GCP_RESERVATION_SHARE_TYPE_ORGANIZATION.
	ShareType *string `json:"shareType,omitempty" tf:"share_type,omitempty"`
}

type ShareSettingsObservation struct {

	// (List of String) Project IDs this reservation is shared with (SPECIFIC_PROJECTS share type only).
	// Project IDs this reservation is shared with (SPECIFIC_PROJECTS share type only).
	ProjectIds []*string `json:"projectIds,omitempty" tf:"project_ids,omitempty"`

	// (String) Share type. One of: GCP_RESERVATION_SHARE_TYPE_LOCAL, GCP_RESERVATION_SHARE_TYPE_SPECIFIC_PROJECTS, GCP_RESERVATION_SHARE_TYPE_ORGANIZATION.
	// Share type. One of: GCP_RESERVATION_SHARE_TYPE_LOCAL, GCP_RESERVATION_SHARE_TYPE_SPECIFIC_PROJECTS, GCP_RESERVATION_SHARE_TYPE_ORGANIZATION.
	ShareType *string `json:"shareType,omitempty" tf:"share_type,omitempty"`
}

type ShareSettingsParameters struct {

	// (List of String) Project IDs this reservation is shared with (SPECIFIC_PROJECTS share type only).
	// Project IDs this reservation is shared with (SPECIFIC_PROJECTS share type only).
	// +kubebuilder:validation:Optional
	ProjectIds []*string `json:"projectIds,omitempty" tf:"project_ids,omitempty"`

	// (String) Share type. One of: GCP_RESERVATION_SHARE_TYPE_LOCAL, GCP_RESERVATION_SHARE_TYPE_SPECIFIC_PROJECTS, GCP_RESERVATION_SHARE_TYPE_ORGANIZATION.
	// Share type. One of: GCP_RESERVATION_SHARE_TYPE_LOCAL, GCP_RESERVATION_SHARE_TYPE_SPECIFIC_PROJECTS, GCP_RESERVATION_SHARE_TYPE_ORGANIZATION.
	// +kubebuilder:validation:Optional
	ShareType *string `json:"shareType,omitempty" tf:"share_type,omitempty"`
}

// CommitmentSpec defines the desired state of Commitment
type CommitmentSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CommitmentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CommitmentInitParameters `json:"initProvider,omitempty"`
}

// CommitmentStatus defines the observed state of Commitment.
type CommitmentStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CommitmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Commitment is the Schema for the Commitments API. Manages a single CAST AI commitment (reserved instance, savings plan, CUD, capacity block or capacity reservation) via the pricing v1beta Commitments API. For bulk management, use for_each — see the examples/ directory.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,castai},path=cloudcommitments
type Commitment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.awsCapacityBlockDetails) || (has(self.initProvider) && has(self.initProvider.awsCapacityBlockDetails))",message="spec.forProvider.awsCapacityBlockDetails is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.awsOdcrDetails) || (has(self.initProvider) && has(self.initProvider.awsOdcrDetails))",message="spec.forProvider.awsOdcrDetails is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.awsReservedInstancesDetails) || (has(self.initProvider) && has(self.initProvider.awsReservedInstancesDetails))",message="spec.forProvider.awsReservedInstancesDetails is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.awsSavingsPlanDetails) || (has(self.initProvider) && has(self.initProvider.awsSavingsPlanDetails))",message="spec.forProvider.awsSavingsPlanDetails is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.azureReservationDetails) || (has(self.initProvider) && has(self.initProvider.azureReservationDetails))",message="spec.forProvider.azureReservationDetails is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.azureSavingsPlanDetails) || (has(self.initProvider) && has(self.initProvider.azureSavingsPlanDetails))",message="spec.forProvider.azureSavingsPlanDetails is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.cloud) || (has(self.initProvider) && has(self.initProvider.cloud))",message="spec.forProvider.cloud is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.gcpCapacityReservationDetails) || (has(self.initProvider) && has(self.initProvider.gcpCapacityReservationDetails))",message="spec.forProvider.gcpCapacityReservationDetails is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.gcpFlexCudDetails) || (has(self.initProvider) && has(self.initProvider.gcpFlexCudDetails))",message="spec.forProvider.gcpFlexCudDetails is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.gcpResourceCudDetails) || (has(self.initProvider) && has(self.initProvider.gcpResourceCudDetails))",message="spec.forProvider.gcpResourceCudDetails is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.region) || (has(self.initProvider) && has(self.initProvider.region))",message="spec.forProvider.region is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.startTime) || (has(self.initProvider) && has(self.initProvider.startTime))",message="spec.forProvider.startTime is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   CommitmentSpec   `json:"spec"`
	Status CommitmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CommitmentList contains a list of Commitments
type CommitmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Commitment `json:"items"`
}

// Repository type metadata.
var (
	Commitment_Kind             = "Commitment"
	Commitment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Commitment_Kind}.String()
	Commitment_KindAPIVersion   = Commitment_Kind + "." + CRDGroupVersion.String()
	Commitment_GroupVersionKind = CRDGroupVersion.WithKind(Commitment_Kind)
)

func init() {
	SchemeBuilder.Register(&Commitment{}, &CommitmentList{})
}
