/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type EdgeConfigurationDefaultInitParameters struct {

	// CAST AI cluster ID
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/crossplane-provider-castai/apis/castai/v1alpha1.OmniCluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a OmniCluster in castai to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a OmniCluster in castai to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// ID of the edge configuration to set as default
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/crossplane-provider-castai/apis/castai/v1alpha1.EdgeConfiguration
	ConfigurationID *string `json:"configurationId,omitempty" tf:"configuration_id,omitempty"`

	// Reference to a EdgeConfiguration in castai to populate configurationId.
	// +kubebuilder:validation:Optional
	ConfigurationIDRef *v1.Reference `json:"configurationIdRef,omitempty" tf:"-"`

	// Selector for a EdgeConfiguration in castai to populate configurationId.
	// +kubebuilder:validation:Optional
	ConfigurationIDSelector *v1.Selector `json:"configurationIdSelector,omitempty" tf:"-"`

	// Edge location ID
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/crossplane-provider-castai/apis/castai/v1alpha1.EdgeLocation
	EdgeLocationID *string `json:"edgeLocationId,omitempty" tf:"edge_location_id,omitempty"`

	// Reference to a EdgeLocation in castai to populate edgeLocationId.
	// +kubebuilder:validation:Optional
	EdgeLocationIDRef *v1.Reference `json:"edgeLocationIdRef,omitempty" tf:"-"`

	// Selector for a EdgeLocation in castai to populate edgeLocationId.
	// +kubebuilder:validation:Optional
	EdgeLocationIDSelector *v1.Selector `json:"edgeLocationIdSelector,omitempty" tf:"-"`

	// CAST AI organization ID
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`
}

type EdgeConfigurationDefaultObservation struct {

	// Cloud provider type (gcp, aws, oci, custom)
	CloudProvider *string `json:"cloudProvider,omitempty" tf:"cloud_provider,omitempty"`

	// CAST AI cluster ID
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// ID of the edge configuration to set as default
	ConfigurationID *string `json:"configurationId,omitempty" tf:"configuration_id,omitempty"`

	// Edge location ID
	EdgeLocationID *string `json:"edgeLocationId,omitempty" tf:"edge_location_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Name of the edge configuration
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// CAST AI organization ID
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`
}

type EdgeConfigurationDefaultParameters struct {

	// CAST AI cluster ID
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/crossplane-provider-castai/apis/castai/v1alpha1.OmniCluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a OmniCluster in castai to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a OmniCluster in castai to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// ID of the edge configuration to set as default
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/crossplane-provider-castai/apis/castai/v1alpha1.EdgeConfiguration
	// +kubebuilder:validation:Optional
	ConfigurationID *string `json:"configurationId,omitempty" tf:"configuration_id,omitempty"`

	// Reference to a EdgeConfiguration in castai to populate configurationId.
	// +kubebuilder:validation:Optional
	ConfigurationIDRef *v1.Reference `json:"configurationIdRef,omitempty" tf:"-"`

	// Selector for a EdgeConfiguration in castai to populate configurationId.
	// +kubebuilder:validation:Optional
	ConfigurationIDSelector *v1.Selector `json:"configurationIdSelector,omitempty" tf:"-"`

	// Edge location ID
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/crossplane-provider-castai/apis/castai/v1alpha1.EdgeLocation
	// +kubebuilder:validation:Optional
	EdgeLocationID *string `json:"edgeLocationId,omitempty" tf:"edge_location_id,omitempty"`

	// Reference to a EdgeLocation in castai to populate edgeLocationId.
	// +kubebuilder:validation:Optional
	EdgeLocationIDRef *v1.Reference `json:"edgeLocationIdRef,omitempty" tf:"-"`

	// Selector for a EdgeLocation in castai to populate edgeLocationId.
	// +kubebuilder:validation:Optional
	EdgeLocationIDSelector *v1.Selector `json:"edgeLocationIdSelector,omitempty" tf:"-"`

	// CAST AI organization ID
	// +kubebuilder:validation:Optional
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`
}

// EdgeConfigurationDefaultSpec defines the desired state of EdgeConfigurationDefault
type EdgeConfigurationDefaultSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     EdgeConfigurationDefaultParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider EdgeConfigurationDefaultInitParameters `json:"initProvider,omitempty"`
}

// EdgeConfigurationDefaultStatus defines the observed state of EdgeConfigurationDefault.
type EdgeConfigurationDefaultStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        EdgeConfigurationDefaultObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// EdgeConfigurationDefault is the Schema for the EdgeConfigurationDefaults API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,castai}
type EdgeConfigurationDefault struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.organizationId) || (has(self.initProvider) && has(self.initProvider.organizationId))",message="spec.forProvider.organizationId is a required parameter"
	Spec   EdgeConfigurationDefaultSpec   `json:"spec"`
	Status EdgeConfigurationDefaultStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EdgeConfigurationDefaultList contains a list of EdgeConfigurationDefaults
type EdgeConfigurationDefaultList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []EdgeConfigurationDefault `json:"items"`
}

// Repository type metadata.
var (
	EdgeConfigurationDefault_Kind             = "EdgeConfigurationDefault"
	EdgeConfigurationDefault_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: EdgeConfigurationDefault_Kind}.String()
	EdgeConfigurationDefault_KindAPIVersion   = EdgeConfigurationDefault_Kind + "." + CRDGroupVersion.String()
	EdgeConfigurationDefault_GroupVersionKind = CRDGroupVersion.WithKind(EdgeConfigurationDefault_Kind)
)

func init() {
	SchemeBuilder.Register(&EdgeConfigurationDefault{}, &EdgeConfigurationDefaultList{})
}
