/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type EksClusterObservation struct {

	// ID of AWS account
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// AWS IAM role ARN that will be assumed by CAST AI user. This role should allow `sts:AssumeRole` action for CAST AI user that can be retrieved using `castai_eks_user_arn` data source
	AssumeRoleArn *string `json:"assumeRoleArn,omitempty" tf:"assume_role_arn,omitempty"`

	// CAST AI internal credentials ID
	CredentialsID *string `json:"credentialsId,omitempty" tf:"credentials_id,omitempty"`

	// Should CAST AI remove nodes managed by CAST AI on disconnect
	DeleteNodesOnDisconnect *bool `json:"deleteNodesOnDisconnect,omitempty" tf:"delete_nodes_on_disconnect,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// name of your EKS cluster
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// AWS region where the cluster is placed
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type EksClusterParameters struct {

	// ID of AWS account
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// AWS IAM role ARN that will be assumed by CAST AI user. This role should allow `sts:AssumeRole` action for CAST AI user that can be retrieved using `castai_eks_user_arn` data source
	// +kubebuilder:validation:Optional
	AssumeRoleArn *string `json:"assumeRoleArn,omitempty" tf:"assume_role_arn,omitempty"`

	// Should CAST AI remove nodes managed by CAST AI on disconnect
	// +kubebuilder:validation:Optional
	DeleteNodesOnDisconnect *bool `json:"deleteNodesOnDisconnect,omitempty" tf:"delete_nodes_on_disconnect,omitempty"`

	// name of your EKS cluster
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// AWS region where the cluster is placed
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

// EksClusterSpec defines the desired state of EksCluster
type EksClusterSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     EksClusterParameters `json:"forProvider"`
}

// EksClusterStatus defines the observed state of EksCluster.
type EksClusterStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        EksClusterObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// EksCluster is the Schema for the EksClusters API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,castai}
type EksCluster struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.accountId)",message="accountId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.name)",message="name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.region)",message="region is a required parameter"
	Spec   EksClusterSpec   `json:"spec"`
	Status EksClusterStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EksClusterList contains a list of EksClusters
type EksClusterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []EksCluster `json:"items"`
}

// Repository type metadata.
var (
	EksCluster_Kind             = "EksCluster"
	EksCluster_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: EksCluster_Kind}.String()
	EksCluster_KindAPIVersion   = EksCluster_Kind + "." + CRDGroupVersion.String()
	EksCluster_GroupVersionKind = CRDGroupVersion.WithKind(EksCluster_Kind)
)

func init() {
	SchemeBuilder.Register(&EksCluster{}, &EksClusterList{})
}
