/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AddonsInitParameters struct {

	// (String) Name of the edge location. Must be unique and relatively short as it's used for creating service accounts.
	// Addon identifier. One of: nvidia-gpu-operator, nvidia-dra, nvidia-network-operator, oci-csi.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// merged over the chart's default values.
	// Helm values for the addon, encoded as a JSON object. Deep-merged over the chart's default values.
	Values *string `json:"values,omitempty" tf:"values,omitempty"`
}

type AddonsObservation struct {

	// (String) Name of the edge location. Must be unique and relatively short as it's used for creating service accounts.
	// Addon identifier. One of: nvidia-gpu-operator, nvidia-dra, nvidia-network-operator, oci-csi.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// merged over the chart's default values.
	// Helm values for the addon, encoded as a JSON object. Deep-merged over the chart's default values.
	Values *string `json:"values,omitempty" tf:"values,omitempty"`
}

type AddonsParameters struct {

	// (String) Name of the edge location. Must be unique and relatively short as it's used for creating service accounts.
	// Addon identifier. One of: nvidia-gpu-operator, nvidia-dra, nvidia-network-operator, oci-csi.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// merged over the chart's default values.
	// Helm values for the addon, encoded as a JSON object. Deep-merged over the chart's default values.
	// +kubebuilder:validation:Optional
	Values *string `json:"values,omitempty" tf:"values,omitempty"`
}

type CniInitParameters struct {

	// router pod-to-pod traffic. Valid values: OVERLAY_UNSPECIFIED, OVERLAY_OFF, OVERLAY_SUBNET, OVERLAY_FULL.
	// Overlay mode for kube-router pod-to-pod traffic. Valid values: OVERLAY_UNSPECIFIED, OVERLAY_OFF, OVERLAY_SUBNET, OVERLAY_FULL.
	Overlay *string `json:"overlay,omitempty" tf:"overlay,omitempty"`

	// (String) Encapsulation protocol used by the overlay. Valid values: OVERLAY_ENCAP_UNSPECIFIED, OVERLAY_ENCAP_IPIP, OVERLAY_ENCAP_FOU.
	// Encapsulation protocol used by the overlay. Valid values: OVERLAY_ENCAP_UNSPECIFIED, OVERLAY_ENCAP_IPIP, OVERLAY_ENCAP_FOU.
	OverlayEncap *string `json:"overlayEncap,omitempty" tf:"overlay_encap,omitempty"`
}

type CniObservation struct {

	// router pod-to-pod traffic. Valid values: OVERLAY_UNSPECIFIED, OVERLAY_OFF, OVERLAY_SUBNET, OVERLAY_FULL.
	// Overlay mode for kube-router pod-to-pod traffic. Valid values: OVERLAY_UNSPECIFIED, OVERLAY_OFF, OVERLAY_SUBNET, OVERLAY_FULL.
	Overlay *string `json:"overlay,omitempty" tf:"overlay,omitempty"`

	// (String) Encapsulation protocol used by the overlay. Valid values: OVERLAY_ENCAP_UNSPECIFIED, OVERLAY_ENCAP_IPIP, OVERLAY_ENCAP_FOU.
	// Encapsulation protocol used by the overlay. Valid values: OVERLAY_ENCAP_UNSPECIFIED, OVERLAY_ENCAP_IPIP, OVERLAY_ENCAP_FOU.
	OverlayEncap *string `json:"overlayEncap,omitempty" tf:"overlay_encap,omitempty"`
}

type CniParameters struct {

	// router pod-to-pod traffic. Valid values: OVERLAY_UNSPECIFIED, OVERLAY_OFF, OVERLAY_SUBNET, OVERLAY_FULL.
	// Overlay mode for kube-router pod-to-pod traffic. Valid values: OVERLAY_UNSPECIFIED, OVERLAY_OFF, OVERLAY_SUBNET, OVERLAY_FULL.
	// +kubebuilder:validation:Optional
	Overlay *string `json:"overlay,omitempty" tf:"overlay,omitempty"`

	// (String) Encapsulation protocol used by the overlay. Valid values: OVERLAY_ENCAP_UNSPECIFIED, OVERLAY_ENCAP_IPIP, OVERLAY_ENCAP_FOU.
	// Encapsulation protocol used by the overlay. Valid values: OVERLAY_ENCAP_UNSPECIFIED, OVERLAY_ENCAP_IPIP, OVERLAY_ENCAP_FOU.
	// +kubebuilder:validation:Optional
	OverlayEncap *string `json:"overlayEncap,omitempty" tf:"overlay_encap,omitempty"`
}

type ControlPlaneInitParameters struct {

	// (Boolean) Whether to use HA mode for control plane. If not set, default is HA.
	// Whether to use HA mode for control plane. If not set, default is HA.
	Ha *bool `json:"ha,omitempty" tf:"ha,omitempty"`
}

type ControlPlaneObservation struct {

	// (Boolean) Whether to use HA mode for control plane. If not set, default is HA.
	// Whether to use HA mode for control plane. If not set, default is HA.
	Ha *bool `json:"ha,omitempty" tf:"ha,omitempty"`
}

type ControlPlaneParameters struct {

	// (Boolean) Whether to use HA mode for control plane. If not set, default is HA.
	// Whether to use HA mode for control plane. If not set, default is HA.
	// +kubebuilder:validation:Optional
	Ha *bool `json:"ha,omitempty" tf:"ha,omitempty"`
}

type EdgeLocationAwsInitParameters struct {

	// (String, Sensitive) AWS access key ID
	// AWS access key ID
	AccessKeyIDWoSecretRef *v1.SecretKeySelector `json:"accessKeyIdWoSecretRef,omitempty" tf:"-"`

	// (String) AWS account ID
	// AWS account ID
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (String) AWS IAM instance profile ARN to be attached to edge instances. It can be used to grant permissions to access other AWS resources such as ECR.
	// AWS IAM instance profile ARN to be attached to edge instances. It can be used to grant permissions to access other AWS resources such as ECR.
	InstanceProfile *string `json:"instanceProfile,omitempty" tf:"instance_profile,omitempty"`

	// (String, Deprecated) The value of a 'Name' tag applied to VPC resources
	// The value of a 'Name' tag applied to VPC resources
	NameTag *string `json:"nameTag,omitempty" tf:"name_tag,omitempty"`

	// (String) AWS IAM role ARN used for Google OIDC federation impersonation
	// AWS IAM role ARN used for Google OIDC federation impersonation
	RoleArn *string `json:"roleArn,omitempty" tf:"role_arn,omitempty"`

	// (String, Sensitive) AWS secret access key
	// AWS secret access key
	SecretAccessKeyWoSecretRef *v1.SecretKeySelector `json:"secretAccessKeyWoSecretRef,omitempty" tf:"-"`

	// (String) Security group ID to be used in the selected region
	// Security group ID to be used in the selected region
	SecurityGroupID *string `json:"securityGroupId,omitempty" tf:"security_group_id,omitempty"`

	// (Map of String) Map of zone names to subnet IDs to be used in the selected region
	// Map of zone names to subnet IDs to be used in the selected region
	// +mapType=granular
	SubnetIds map[string]*string `json:"subnetIds,omitempty" tf:"subnet_ids,omitempty"`

	// (String) VPC IPv4 CIDR block
	// VPC IPv4 CIDR block
	VPCCidr *string `json:"vpcCidr,omitempty" tf:"vpc_cidr,omitempty"`

	// (String) VPC ID to be used in the selected region
	// VPC ID to be used in the selected region
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`

	// (Boolean) Whether existing VPC is peered with main cluster's VPC. Field is ignored if vpc_id is not provided or main cluster is not EKS
	// Whether existing VPC is peered with main cluster's VPC. Field is ignored if vpc_id is not provided or main cluster is not EKS
	VPCPeered *bool `json:"vpcPeered,omitempty" tf:"vpc_peered,omitempty"`
}

type EdgeLocationAwsObservation struct {

	// (String) AWS account ID
	// AWS account ID
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (String) AWS IAM instance profile ARN to be attached to edge instances. It can be used to grant permissions to access other AWS resources such as ECR.
	// AWS IAM instance profile ARN to be attached to edge instances. It can be used to grant permissions to access other AWS resources such as ECR.
	InstanceProfile *string `json:"instanceProfile,omitempty" tf:"instance_profile,omitempty"`

	// (String, Deprecated) The value of a 'Name' tag applied to VPC resources
	// The value of a 'Name' tag applied to VPC resources
	NameTag *string `json:"nameTag,omitempty" tf:"name_tag,omitempty"`

	// (String) AWS IAM role ARN used for Google OIDC federation impersonation
	// AWS IAM role ARN used for Google OIDC federation impersonation
	RoleArn *string `json:"roleArn,omitempty" tf:"role_arn,omitempty"`

	// (String) Security group ID to be used in the selected region
	// Security group ID to be used in the selected region
	SecurityGroupID *string `json:"securityGroupId,omitempty" tf:"security_group_id,omitempty"`

	// (Map of String) Map of zone names to subnet IDs to be used in the selected region
	// Map of zone names to subnet IDs to be used in the selected region
	// +mapType=granular
	SubnetIds map[string]*string `json:"subnetIds,omitempty" tf:"subnet_ids,omitempty"`

	// (String) VPC IPv4 CIDR block
	// VPC IPv4 CIDR block
	VPCCidr *string `json:"vpcCidr,omitempty" tf:"vpc_cidr,omitempty"`

	// (String) VPC ID to be used in the selected region
	// VPC ID to be used in the selected region
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`

	// (Boolean) Whether existing VPC is peered with main cluster's VPC. Field is ignored if vpc_id is not provided or main cluster is not EKS
	// Whether existing VPC is peered with main cluster's VPC. Field is ignored if vpc_id is not provided or main cluster is not EKS
	VPCPeered *bool `json:"vpcPeered,omitempty" tf:"vpc_peered,omitempty"`
}

type EdgeLocationAwsParameters struct {

	// (String, Sensitive) AWS access key ID
	// AWS access key ID
	// +kubebuilder:validation:Optional
	AccessKeyIDWoSecretRef *v1.SecretKeySelector `json:"accessKeyIdWoSecretRef,omitempty" tf:"-"`

	// (String) AWS account ID
	// AWS account ID
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (String) AWS IAM instance profile ARN to be attached to edge instances. It can be used to grant permissions to access other AWS resources such as ECR.
	// AWS IAM instance profile ARN to be attached to edge instances. It can be used to grant permissions to access other AWS resources such as ECR.
	// +kubebuilder:validation:Optional
	InstanceProfile *string `json:"instanceProfile,omitempty" tf:"instance_profile,omitempty"`

	// (String, Deprecated) The value of a 'Name' tag applied to VPC resources
	// The value of a 'Name' tag applied to VPC resources
	// +kubebuilder:validation:Optional
	NameTag *string `json:"nameTag,omitempty" tf:"name_tag,omitempty"`

	// (String) AWS IAM role ARN used for Google OIDC federation impersonation
	// AWS IAM role ARN used for Google OIDC federation impersonation
	// +kubebuilder:validation:Optional
	RoleArn *string `json:"roleArn,omitempty" tf:"role_arn,omitempty"`

	// (String, Sensitive) AWS secret access key
	// AWS secret access key
	// +kubebuilder:validation:Optional
	SecretAccessKeyWoSecretRef *v1.SecretKeySelector `json:"secretAccessKeyWoSecretRef,omitempty" tf:"-"`

	// (String) Security group ID to be used in the selected region
	// Security group ID to be used in the selected region
	// +kubebuilder:validation:Optional
	SecurityGroupID *string `json:"securityGroupId,omitempty" tf:"security_group_id,omitempty"`

	// (Map of String) Map of zone names to subnet IDs to be used in the selected region
	// Map of zone names to subnet IDs to be used in the selected region
	// +kubebuilder:validation:Optional
	// +mapType=granular
	SubnetIds map[string]*string `json:"subnetIds,omitempty" tf:"subnet_ids,omitempty"`

	// (String) VPC IPv4 CIDR block
	// VPC IPv4 CIDR block
	// +kubebuilder:validation:Optional
	VPCCidr *string `json:"vpcCidr,omitempty" tf:"vpc_cidr,omitempty"`

	// (String) VPC ID to be used in the selected region
	// VPC ID to be used in the selected region
	// +kubebuilder:validation:Optional
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`

	// (Boolean) Whether existing VPC is peered with main cluster's VPC. Field is ignored if vpc_id is not provided or main cluster is not EKS
	// Whether existing VPC is peered with main cluster's VPC. Field is ignored if vpc_id is not provided or main cluster is not EKS
	// +kubebuilder:validation:Optional
	VPCPeered *bool `json:"vpcPeered,omitempty" tf:"vpc_peered,omitempty"`
}

type EdgeLocationCustomInitParameters struct {
}

type EdgeLocationCustomObservation struct {
}

type EdgeLocationCustomParameters struct {
}

type EdgeLocationGCPInitParameters struct {

	// (String, Sensitive) Base64 encoded service account JSON for provisioning edge resources
	// Base64 encoded service account JSON for provisioning edge resources
	ClientServiceAccountJSONBase64WoSecretRef *v1.SecretKeySelector `json:"clientServiceAccountJsonBase64WoSecretRef,omitempty" tf:"-"`

	// (String) GCP service account email to be attached to edge instances. It can be used to grant permissions to access other GCP resources.
	// GCP service account email to be attached to edge instances. It can be used to grant permissions to access other GCP resources.
	InstanceServiceAccount *string `json:"instanceServiceAccount,omitempty" tf:"instance_service_account,omitempty"`

	// (String) The name of the network to be used in the selected region
	// The name of the network to be used in the selected region
	NetworkName *string `json:"networkName,omitempty" tf:"network_name,omitempty"`

	// (Set of String) Tags applied on the provisioned cloud resources and the firewall rule
	// Tags applied on the provisioned cloud resources and the firewall rule
	// +listType=set
	NetworkTags []*string `json:"networkTags,omitempty" tf:"network_tags,omitempty"`

	// (String) GCP project ID where edges run
	// GCP project ID where edges run
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) VPC Subnet IPv4 CIDR block
	// VPC Subnet IPv4 CIDR block
	SubnetCidr *string `json:"subnetCidr,omitempty" tf:"subnet_cidr,omitempty"`

	// (String) The name of the subnetwork to be used in the selected region
	// The name of the subnetwork to be used in the selected region
	SubnetName *string `json:"subnetName,omitempty" tf:"subnet_name,omitempty"`

	// (String) Target service account email to be used for impersonation
	// Target service account email to be used for impersonation
	TargetServiceAccountEmail *string `json:"targetServiceAccountEmail,omitempty" tf:"target_service_account_email,omitempty"`
}

type EdgeLocationGCPObservation struct {

	// (String) GCP service account email to be attached to edge instances. It can be used to grant permissions to access other GCP resources.
	// GCP service account email to be attached to edge instances. It can be used to grant permissions to access other GCP resources.
	InstanceServiceAccount *string `json:"instanceServiceAccount,omitempty" tf:"instance_service_account,omitempty"`

	// (String) The name of the network to be used in the selected region
	// The name of the network to be used in the selected region
	NetworkName *string `json:"networkName,omitempty" tf:"network_name,omitempty"`

	// (Set of String) Tags applied on the provisioned cloud resources and the firewall rule
	// Tags applied on the provisioned cloud resources and the firewall rule
	// +listType=set
	NetworkTags []*string `json:"networkTags,omitempty" tf:"network_tags,omitempty"`

	// (String) GCP project ID where edges run
	// GCP project ID where edges run
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) VPC Subnet IPv4 CIDR block
	// VPC Subnet IPv4 CIDR block
	SubnetCidr *string `json:"subnetCidr,omitempty" tf:"subnet_cidr,omitempty"`

	// (String) The name of the subnetwork to be used in the selected region
	// The name of the subnetwork to be used in the selected region
	SubnetName *string `json:"subnetName,omitempty" tf:"subnet_name,omitempty"`

	// (String) Target service account email to be used for impersonation
	// Target service account email to be used for impersonation
	TargetServiceAccountEmail *string `json:"targetServiceAccountEmail,omitempty" tf:"target_service_account_email,omitempty"`
}

type EdgeLocationGCPParameters struct {

	// (String, Sensitive) Base64 encoded service account JSON for provisioning edge resources
	// Base64 encoded service account JSON for provisioning edge resources
	// +kubebuilder:validation:Optional
	ClientServiceAccountJSONBase64WoSecretRef *v1.SecretKeySelector `json:"clientServiceAccountJsonBase64WoSecretRef,omitempty" tf:"-"`

	// (String) GCP service account email to be attached to edge instances. It can be used to grant permissions to access other GCP resources.
	// GCP service account email to be attached to edge instances. It can be used to grant permissions to access other GCP resources.
	// +kubebuilder:validation:Optional
	InstanceServiceAccount *string `json:"instanceServiceAccount,omitempty" tf:"instance_service_account,omitempty"`

	// (String) The name of the network to be used in the selected region
	// The name of the network to be used in the selected region
	// +kubebuilder:validation:Optional
	NetworkName *string `json:"networkName,omitempty" tf:"network_name,omitempty"`

	// (Set of String) Tags applied on the provisioned cloud resources and the firewall rule
	// Tags applied on the provisioned cloud resources and the firewall rule
	// +kubebuilder:validation:Optional
	// +listType=set
	NetworkTags []*string `json:"networkTags,omitempty" tf:"network_tags,omitempty"`

	// (String) GCP project ID where edges run
	// GCP project ID where edges run
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) VPC Subnet IPv4 CIDR block
	// VPC Subnet IPv4 CIDR block
	// +kubebuilder:validation:Optional
	SubnetCidr *string `json:"subnetCidr,omitempty" tf:"subnet_cidr,omitempty"`

	// (String) The name of the subnetwork to be used in the selected region
	// The name of the subnetwork to be used in the selected region
	// +kubebuilder:validation:Optional
	SubnetName *string `json:"subnetName,omitempty" tf:"subnet_name,omitempty"`

	// (String) Target service account email to be used for impersonation
	// Target service account email to be used for impersonation
	// +kubebuilder:validation:Optional
	TargetServiceAccountEmail *string `json:"targetServiceAccountEmail,omitempty" tf:"target_service_account_email,omitempty"`
}

type EdgeLocationInitParameters struct {

	// gpu-operator. Set to an empty list to install no optional addons. (see below for nested schema)
	// Optional addons to install on the edge cluster. Defaults to installing nvidia-gpu-operator. Set to an empty list to install no optional addons.
	Addons []AddonsInitParameters `json:"addons,omitempty" tf:"addons,omitempty"`

	// (Attributes) AWS configuration for the edge location (see below for nested schema)
	// AWS configuration for the edge location
	Aws *EdgeLocationAwsInitParameters `json:"aws,omitempty" tf:"aws,omitempty"`

	// (String) CAST AI cluster ID
	// CAST AI cluster ID
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/crossplane-provider-castai/apis/castai/v1alpha1.OmniCluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a OmniCluster in castai to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a OmniCluster in castai to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (Attributes) Control plane configuration. Only valid when control_plane_mode is SHARED. (see below for nested schema)
	// Control plane configuration. Only valid when control_plane_mode is SHARED.
	ControlPlane *ControlPlaneInitParameters `json:"controlPlane,omitempty" tf:"control_plane,omitempty"`

	// (String) The mode of control plane inside edge location. Valid values: DEDICATED, SHARED.
	// The mode of control plane inside edge location. Valid values: DEDICATED, SHARED.
	ControlPlaneMode *string `json:"controlPlaneMode,omitempty" tf:"control_plane_mode,omitempty"`

	// (Attributes) Custom cloud provider configuration for the edge location (see below for nested schema)
	// Custom cloud provider configuration for the edge location
	Custom *EdgeLocationCustomInitParameters `json:"custom,omitempty" tf:"custom,omitempty"`

	// (String) Description of the edge location
	// Description of the edge location
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Attributes) GCP configuration for the edge location (see below for nested schema)
	// GCP configuration for the edge location
	GCP *EdgeLocationGCPInitParameters `json:"gcp,omitempty" tf:"gcp,omitempty"`

	// (String) Name of the edge location. Must be unique and relatively short as it's used for creating service accounts.
	// Name of the edge location. Must be unique and relatively short as it's used for creating service accounts.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) Edge cluster networking configuration. (see below for nested schema)
	// Edge cluster networking configuration.
	Networking *NetworkingInitParameters `json:"networking,omitempty" tf:"networking,omitempty"`

	// (Attributes) OCI configuration for the edge location (see below for nested schema)
	// OCI configuration for the edge location
	Oci *EdgeLocationOciInitParameters `json:"oci,omitempty" tf:"oci,omitempty"`

	// (String) CAST AI organization ID
	// CAST AI organization ID
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// (String) The region where the edge location is deployed. Required for AWS, GCP and OCI providers.
	// The region where the edge location is deployed. Required for AWS, GCP and OCI providers.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (Attributes List) List of availability zones for the edge location (see below for nested schema)
	// List of availability zones for the edge location
	Zones []ZonesInitParameters `json:"zones,omitempty" tf:"zones,omitempty"`
}

type EdgeLocationObservation struct {

	// gpu-operator. Set to an empty list to install no optional addons. (see below for nested schema)
	// Optional addons to install on the edge cluster. Defaults to installing nvidia-gpu-operator. Set to an empty list to install no optional addons.
	Addons []AddonsObservation `json:"addons,omitempty" tf:"addons,omitempty"`

	// (Attributes) AWS configuration for the edge location (see below for nested schema)
	// AWS configuration for the edge location
	Aws *EdgeLocationAwsObservation `json:"aws,omitempty" tf:"aws,omitempty"`

	// (String) CAST AI cluster ID
	// CAST AI cluster ID
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (Attributes) Control plane configuration. Only valid when control_plane_mode is SHARED. (see below for nested schema)
	// Control plane configuration. Only valid when control_plane_mode is SHARED.
	ControlPlane *ControlPlaneObservation `json:"controlPlane,omitempty" tf:"control_plane,omitempty"`

	// (String) The mode of control plane inside edge location. Valid values: DEDICATED, SHARED.
	// The mode of control plane inside edge location. Valid values: DEDICATED, SHARED.
	ControlPlaneMode *string `json:"controlPlaneMode,omitempty" tf:"control_plane_mode,omitempty"`

	// (Number) Revision number incremented each time credentials change
	// Revision number incremented each time credentials change
	CredentialsRevision *float64 `json:"credentialsRevision,omitempty" tf:"credentials_revision,omitempty"`

	// (Attributes) Custom cloud provider configuration for the edge location (see below for nested schema)
	// Custom cloud provider configuration for the edge location
	Custom *EdgeLocationCustomParameters `json:"custom,omitempty" tf:"custom,omitempty"`

	// (String) Description of the edge location
	// Description of the edge location
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Attributes) GCP configuration for the edge location (see below for nested schema)
	// GCP configuration for the edge location
	GCP *EdgeLocationGCPObservation `json:"gcp,omitempty" tf:"gcp,omitempty"`

	// (String) Edge location ID
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Name of the edge location. Must be unique and relatively short as it's used for creating service accounts.
	// Name of the edge location. Must be unique and relatively short as it's used for creating service accounts.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) Edge cluster networking configuration. (see below for nested schema)
	// Edge cluster networking configuration.
	Networking *NetworkingObservation `json:"networking,omitempty" tf:"networking,omitempty"`

	// (Attributes) OCI configuration for the edge location (see below for nested schema)
	// OCI configuration for the edge location
	Oci *EdgeLocationOciObservation `json:"oci,omitempty" tf:"oci,omitempty"`

	// (String) CAST AI organization ID
	// CAST AI organization ID
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// (String) The region where the edge location is deployed. Required for AWS, GCP and OCI providers.
	// The region where the edge location is deployed. Required for AWS, GCP and OCI providers.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (Attributes List) List of availability zones for the edge location (see below for nested schema)
	// List of availability zones for the edge location
	Zones []ZonesObservation `json:"zones,omitempty" tf:"zones,omitempty"`
}

type EdgeLocationOciInitParameters struct {

	// (String) OCI compartment ID of edge location
	// OCI compartment ID of edge location
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// (String, Sensitive) API key fingerprint
	// API key fingerprint
	FingerprintWoSecretRef *v1.SecretKeySelector `json:"fingerprintWoSecretRef,omitempty" tf:"-"`

	// (String, Sensitive) Base64 encoded API private key
	// Base64 encoded API private key
	PrivateKeyBase64WoSecretRef *v1.SecretKeySelector `json:"privateKeyBase64WoSecretRef,omitempty" tf:"-"`

	// (String) Security group ID to be used in the selected region
	// OCI network security group ID
	SecurityGroupID *string `json:"securityGroupId,omitempty" tf:"security_group_id,omitempty"`

	// (String) OCI subnet ID of edge location
	// OCI subnet ID of edge location
	SubnetID *string `json:"subnetId,omitempty" tf:"subnet_id,omitempty"`

	// (String) OCI tenancy ID of the account
	// OCI tenancy ID of the account
	TenancyID *string `json:"tenancyId,omitempty" tf:"tenancy_id,omitempty"`

	// (String) User ID used to authenticate OCI
	// User ID used to authenticate OCI
	UserIDWo *string `json:"userIdWo,omitempty" tf:"user_id_wo,omitempty"`

	// (String) OCI VCN IPv4 CIDR block
	// OCI VCN IPv4 CIDR block
	VcnCidr *string `json:"vcnCidr,omitempty" tf:"vcn_cidr,omitempty"`

	// (String) OCI virtual cloud network ID
	// OCI virtual cloud network ID
	VcnID *string `json:"vcnId,omitempty" tf:"vcn_id,omitempty"`
}

type EdgeLocationOciObservation struct {

	// (String) OCI compartment ID of edge location
	// OCI compartment ID of edge location
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// (String) Security group ID to be used in the selected region
	// OCI network security group ID
	SecurityGroupID *string `json:"securityGroupId,omitempty" tf:"security_group_id,omitempty"`

	// (String) OCI subnet ID of edge location
	// OCI subnet ID of edge location
	SubnetID *string `json:"subnetId,omitempty" tf:"subnet_id,omitempty"`

	// (String) OCI tenancy ID of the account
	// OCI tenancy ID of the account
	TenancyID *string `json:"tenancyId,omitempty" tf:"tenancy_id,omitempty"`

	// (String) User ID used to authenticate OCI
	// User ID used to authenticate OCI
	UserIDWo *string `json:"userIdWo,omitempty" tf:"user_id_wo,omitempty"`

	// (String) OCI VCN IPv4 CIDR block
	// OCI VCN IPv4 CIDR block
	VcnCidr *string `json:"vcnCidr,omitempty" tf:"vcn_cidr,omitempty"`

	// (String) OCI virtual cloud network ID
	// OCI virtual cloud network ID
	VcnID *string `json:"vcnId,omitempty" tf:"vcn_id,omitempty"`
}

type EdgeLocationOciParameters struct {

	// (String) OCI compartment ID of edge location
	// OCI compartment ID of edge location
	// +kubebuilder:validation:Optional
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// (String, Sensitive) API key fingerprint
	// API key fingerprint
	// +kubebuilder:validation:Optional
	FingerprintWoSecretRef *v1.SecretKeySelector `json:"fingerprintWoSecretRef,omitempty" tf:"-"`

	// (String, Sensitive) Base64 encoded API private key
	// Base64 encoded API private key
	// +kubebuilder:validation:Optional
	PrivateKeyBase64WoSecretRef *v1.SecretKeySelector `json:"privateKeyBase64WoSecretRef,omitempty" tf:"-"`

	// (String) Security group ID to be used in the selected region
	// OCI network security group ID
	// +kubebuilder:validation:Optional
	SecurityGroupID *string `json:"securityGroupId,omitempty" tf:"security_group_id,omitempty"`

	// (String) OCI subnet ID of edge location
	// OCI subnet ID of edge location
	// +kubebuilder:validation:Optional
	SubnetID *string `json:"subnetId,omitempty" tf:"subnet_id,omitempty"`

	// (String) OCI tenancy ID of the account
	// OCI tenancy ID of the account
	// +kubebuilder:validation:Optional
	TenancyID *string `json:"tenancyId,omitempty" tf:"tenancy_id,omitempty"`

	// (String) User ID used to authenticate OCI
	// User ID used to authenticate OCI
	// +kubebuilder:validation:Optional
	UserIDWo *string `json:"userIdWo,omitempty" tf:"user_id_wo,omitempty"`

	// (String) OCI VCN IPv4 CIDR block
	// OCI VCN IPv4 CIDR block
	// +kubebuilder:validation:Optional
	VcnCidr *string `json:"vcnCidr,omitempty" tf:"vcn_cidr,omitempty"`

	// (String) OCI virtual cloud network ID
	// OCI virtual cloud network ID
	// +kubebuilder:validation:Optional
	VcnID *string `json:"vcnId,omitempty" tf:"vcn_id,omitempty"`
}

type EdgeLocationParameters struct {

	// gpu-operator. Set to an empty list to install no optional addons. (see below for nested schema)
	// Optional addons to install on the edge cluster. Defaults to installing nvidia-gpu-operator. Set to an empty list to install no optional addons.
	// +kubebuilder:validation:Optional
	Addons []AddonsParameters `json:"addons,omitempty" tf:"addons,omitempty"`

	// (Attributes) AWS configuration for the edge location (see below for nested schema)
	// AWS configuration for the edge location
	// +kubebuilder:validation:Optional
	Aws *EdgeLocationAwsParameters `json:"aws,omitempty" tf:"aws,omitempty"`

	// (String) CAST AI cluster ID
	// CAST AI cluster ID
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/crossplane-provider-castai/apis/castai/v1alpha1.OmniCluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a OmniCluster in castai to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a OmniCluster in castai to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (Attributes) Control plane configuration. Only valid when control_plane_mode is SHARED. (see below for nested schema)
	// Control plane configuration. Only valid when control_plane_mode is SHARED.
	// +kubebuilder:validation:Optional
	ControlPlane *ControlPlaneParameters `json:"controlPlane,omitempty" tf:"control_plane,omitempty"`

	// (String) The mode of control plane inside edge location. Valid values: DEDICATED, SHARED.
	// The mode of control plane inside edge location. Valid values: DEDICATED, SHARED.
	// +kubebuilder:validation:Optional
	ControlPlaneMode *string `json:"controlPlaneMode,omitempty" tf:"control_plane_mode,omitempty"`

	// (Attributes) Custom cloud provider configuration for the edge location (see below for nested schema)
	// Custom cloud provider configuration for the edge location
	// +kubebuilder:validation:Optional
	Custom *EdgeLocationCustomParameters `json:"custom,omitempty" tf:"custom,omitempty"`

	// (String) Description of the edge location
	// Description of the edge location
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Attributes) GCP configuration for the edge location (see below for nested schema)
	// GCP configuration for the edge location
	// +kubebuilder:validation:Optional
	GCP *EdgeLocationGCPParameters `json:"gcp,omitempty" tf:"gcp,omitempty"`

	// (String) Name of the edge location. Must be unique and relatively short as it's used for creating service accounts.
	// Name of the edge location. Must be unique and relatively short as it's used for creating service accounts.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) Edge cluster networking configuration. (see below for nested schema)
	// Edge cluster networking configuration.
	// +kubebuilder:validation:Optional
	Networking *NetworkingParameters `json:"networking,omitempty" tf:"networking,omitempty"`

	// (Attributes) OCI configuration for the edge location (see below for nested schema)
	// OCI configuration for the edge location
	// +kubebuilder:validation:Optional
	Oci *EdgeLocationOciParameters `json:"oci,omitempty" tf:"oci,omitempty"`

	// (String) CAST AI organization ID
	// CAST AI organization ID
	// +kubebuilder:validation:Optional
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// (String) The region where the edge location is deployed. Required for AWS, GCP and OCI providers.
	// The region where the edge location is deployed. Required for AWS, GCP and OCI providers.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (Attributes List) List of availability zones for the edge location (see below for nested schema)
	// List of availability zones for the edge location
	// +kubebuilder:validation:Optional
	Zones []ZonesParameters `json:"zones,omitempty" tf:"zones,omitempty"`
}

type NetworkingInitParameters struct {

	// router) configuration for the edge cluster. (see below for nested schema)
	// CNI (kube-router) configuration for the edge cluster.
	Cni *CniInitParameters `json:"cni,omitempty" tf:"cni,omitempty"`

	// (List of String) List of destination CIDR blocks whose traffic should be routed through the main cluster instead of directly from the edge cluster.
	// List of destination CIDR blocks whose traffic should be routed through the main cluster instead of directly from the edge cluster.
	TunneledCidrs []*string `json:"tunneledCidrs,omitempty" tf:"tunneled_cidrs,omitempty"`
}

type NetworkingObservation struct {

	// router) configuration for the edge cluster. (see below for nested schema)
	// CNI (kube-router) configuration for the edge cluster.
	Cni *CniObservation `json:"cni,omitempty" tf:"cni,omitempty"`

	// (List of String) List of destination CIDR blocks whose traffic should be routed through the main cluster instead of directly from the edge cluster.
	// List of destination CIDR blocks whose traffic should be routed through the main cluster instead of directly from the edge cluster.
	TunneledCidrs []*string `json:"tunneledCidrs,omitempty" tf:"tunneled_cidrs,omitempty"`
}

type NetworkingParameters struct {

	// router) configuration for the edge cluster. (see below for nested schema)
	// CNI (kube-router) configuration for the edge cluster.
	// +kubebuilder:validation:Optional
	Cni *CniParameters `json:"cni,omitempty" tf:"cni,omitempty"`

	// (List of String) List of destination CIDR blocks whose traffic should be routed through the main cluster instead of directly from the edge cluster.
	// List of destination CIDR blocks whose traffic should be routed through the main cluster instead of directly from the edge cluster.
	// +kubebuilder:validation:Optional
	TunneledCidrs []*string `json:"tunneledCidrs,omitempty" tf:"tunneled_cidrs,omitempty"`
}

type ZonesInitParameters struct {

	// (String) Edge location ID
	// The ID of the zone
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Name of the edge location. Must be unique and relatively short as it's used for creating service accounts.
	// The name of the zone
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type ZonesObservation struct {

	// (String) Edge location ID
	// The ID of the zone
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Name of the edge location. Must be unique and relatively short as it's used for creating service accounts.
	// The name of the zone
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type ZonesParameters struct {

	// (String) Edge location ID
	// The ID of the zone
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// (String) Name of the edge location. Must be unique and relatively short as it's used for creating service accounts.
	// The name of the zone
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`
}

// EdgeLocationSpec defines the desired state of EdgeLocation
type EdgeLocationSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     EdgeLocationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider EdgeLocationInitParameters `json:"initProvider,omitempty"`
}

// EdgeLocationStatus defines the observed state of EdgeLocation.
type EdgeLocationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        EdgeLocationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// EdgeLocation is the Schema for the EdgeLocations API. Manage CAST AI Edge Location for edge computing deployments
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,castai}
type EdgeLocation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.organizationId) || (has(self.initProvider) && has(self.initProvider.organizationId))",message="spec.forProvider.organizationId is a required parameter"
	Spec   EdgeLocationSpec   `json:"spec"`
	Status EdgeLocationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EdgeLocationList contains a list of EdgeLocations
type EdgeLocationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []EdgeLocation `json:"items"`
}

// Repository type metadata.
var (
	EdgeLocation_Kind             = "EdgeLocation"
	EdgeLocation_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: EdgeLocation_Kind}.String()
	EdgeLocation_KindAPIVersion   = EdgeLocation_Kind + "." + CRDGroupVersion.String()
	EdgeLocation_GroupVersionKind = CRDGroupVersion.WithKind(EdgeLocation_Kind)
)

func init() {
	SchemeBuilder.Register(&EdgeLocation{}, &EdgeLocationList{})
}
