/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type CacheGroupInitParameters struct {

	// Enable direct mode for the cache group.
	DirectMode *bool `json:"directMode,omitempty" tf:"direct_mode,omitempty"`

	// Connection endpoints for the cache group. At least one endpoint is required when specified.
	Endpoints []EndpointsInitParameters `json:"endpoints,omitempty" tf:"endpoints,omitempty"`

	// Display name for the cache group.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Database protocol type. Valid values: MySQL or PostgreSQL
	ProtocolType *string `json:"protocolType,omitempty" tf:"protocol_type,omitempty"`
}

type CacheGroupObservation struct {

	// Enable direct mode for the cache group.
	DirectMode *bool `json:"directMode,omitempty" tf:"direct_mode,omitempty"`

	// Connection endpoints for the cache group. At least one endpoint is required when specified.
	Endpoints []EndpointsObservation `json:"endpoints,omitempty" tf:"endpoints,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Display name for the cache group.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Database protocol type. Valid values: MySQL or PostgreSQL
	ProtocolType *string `json:"protocolType,omitempty" tf:"protocol_type,omitempty"`
}

type CacheGroupParameters struct {

	// Enable direct mode for the cache group.
	// +kubebuilder:validation:Optional
	DirectMode *bool `json:"directMode,omitempty" tf:"direct_mode,omitempty"`

	// Connection endpoints for the cache group. At least one endpoint is required when specified.
	// +kubebuilder:validation:Optional
	Endpoints []EndpointsParameters `json:"endpoints,omitempty" tf:"endpoints,omitempty"`

	// Display name for the cache group.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Database protocol type. Valid values: MySQL or PostgreSQL
	// +kubebuilder:validation:Optional
	ProtocolType *string `json:"protocolType,omitempty" tf:"protocol_type,omitempty"`
}

type EndpointsInitParameters struct {

	// Database instance hostname.
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// Name for the endpoint.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Database instance port.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`
}

type EndpointsObservation struct {

	// Database instance hostname.
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// Name for the endpoint.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Database instance port.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`
}

type EndpointsParameters struct {

	// Database instance hostname.
	// +kubebuilder:validation:Optional
	Hostname *string `json:"hostname" tf:"hostname,omitempty"`

	// Name for the endpoint.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// Database instance port.
	// +kubebuilder:validation:Optional
	Port *float64 `json:"port" tf:"port,omitempty"`
}

// CacheGroupSpec defines the desired state of CacheGroup
type CacheGroupSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            CacheGroupParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CacheGroupInitParameters `json:"initProvider,omitempty"`
}

// CacheGroupStatus defines the observed state of CacheGroup.
type CacheGroupStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CacheGroupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CacheGroup is the Schema for the CacheGroups API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,castai}
type CacheGroup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.protocolType) || (has(self.initProvider) && has(self.initProvider.protocolType))",message="spec.forProvider.protocolType is a required parameter"
	Spec   CacheGroupSpec   `json:"spec"`
	Status CacheGroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CacheGroupList contains a list of CacheGroups
type CacheGroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CacheGroup `json:"items"`
}

// Repository type metadata.
var (
	CacheGroup_Kind             = "CacheGroup"
	CacheGroup_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CacheGroup_Kind}.String()
	CacheGroup_KindAPIVersion   = CacheGroup_Kind + "." + CRDGroupVersion.String()
	CacheGroup_GroupVersionKind = CRDGroupVersion.WithKind(CacheGroup_Kind)
)

func init() {
	SchemeBuilder.Register(&CacheGroup{}, &CacheGroupList{})
}
