/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type CacheRuleInitParameters struct {

	// ID of the cache configuration this rule belongs to.
	CacheConfigurationID *string `json:"cacheConfigurationId,omitempty" tf:"cache_configuration_id,omitempty"`

	// ID of the cache group this rule belongs to.
	CacheGroupID *string `json:"cacheGroupId,omitempty" tf:"cache_group_id,omitempty"`

	// TTL in seconds. Required when mode is Manual.
	ManualTTL *float64 `json:"manualTtl,omitempty" tf:"manual_ttl,omitempty"`

	// TTL mode for queries matching this rule. Valid values: Auto, DontCache, Manual.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// Database table name to apply this rule to. Either table or template_hash must be specified.
	Table *string `json:"table,omitempty" tf:"table,omitempty"`

	// Hash of the query template. Either table or template_hash must be specified.
	TemplateHash *string `json:"templateHash,omitempty" tf:"template_hash,omitempty"`
}

type CacheRuleObservation struct {

	// ID of the cache configuration this rule belongs to.
	CacheConfigurationID *string `json:"cacheConfigurationId,omitempty" tf:"cache_configuration_id,omitempty"`

	// ID of the cache group this rule belongs to.
	CacheGroupID *string `json:"cacheGroupId,omitempty" tf:"cache_group_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// TTL in seconds. Required when mode is Manual.
	ManualTTL *float64 `json:"manualTtl,omitempty" tf:"manual_ttl,omitempty"`

	// TTL mode for queries matching this rule. Valid values: Auto, DontCache, Manual.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// Database table name to apply this rule to. Either table or template_hash must be specified.
	Table *string `json:"table,omitempty" tf:"table,omitempty"`

	// Hash of the query template. Either table or template_hash must be specified.
	TemplateHash *string `json:"templateHash,omitempty" tf:"template_hash,omitempty"`
}

type CacheRuleParameters struct {

	// ID of the cache configuration this rule belongs to.
	// +kubebuilder:validation:Optional
	CacheConfigurationID *string `json:"cacheConfigurationId,omitempty" tf:"cache_configuration_id,omitempty"`

	// ID of the cache group this rule belongs to.
	// +kubebuilder:validation:Optional
	CacheGroupID *string `json:"cacheGroupId,omitempty" tf:"cache_group_id,omitempty"`

	// TTL in seconds. Required when mode is Manual.
	// +kubebuilder:validation:Optional
	ManualTTL *float64 `json:"manualTtl,omitempty" tf:"manual_ttl,omitempty"`

	// TTL mode for queries matching this rule. Valid values: Auto, DontCache, Manual.
	// +kubebuilder:validation:Optional
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// Database table name to apply this rule to. Either table or template_hash must be specified.
	// +kubebuilder:validation:Optional
	Table *string `json:"table,omitempty" tf:"table,omitempty"`

	// Hash of the query template. Either table or template_hash must be specified.
	// +kubebuilder:validation:Optional
	TemplateHash *string `json:"templateHash,omitempty" tf:"template_hash,omitempty"`
}

// CacheRuleSpec defines the desired state of CacheRule
type CacheRuleSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            CacheRuleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CacheRuleInitParameters `json:"initProvider,omitempty"`
}

// CacheRuleStatus defines the observed state of CacheRule.
type CacheRuleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CacheRuleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CacheRule is the Schema for the CacheRules API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,castai}
type CacheRule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.cacheConfigurationId) || (has(self.initProvider) && has(self.initProvider.cacheConfigurationId))",message="spec.forProvider.cacheConfigurationId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.cacheGroupId) || (has(self.initProvider) && has(self.initProvider.cacheGroupId))",message="spec.forProvider.cacheGroupId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.mode) || (has(self.initProvider) && has(self.initProvider.mode))",message="spec.forProvider.mode is a required parameter"
	Spec   CacheRuleSpec   `json:"spec"`
	Status CacheRuleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CacheRuleList contains a list of CacheRules
type CacheRuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CacheRule `json:"items"`
}

// Repository type metadata.
var (
	CacheRule_Kind             = "CacheRule"
	CacheRule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CacheRule_Kind}.String()
	CacheRule_KindAPIVersion   = CacheRule_Kind + "." + CRDGroupVersion.String()
	CacheRule_GroupVersionKind = CRDGroupVersion.WithKind(CacheRule_Kind)
)

func init() {
	SchemeBuilder.Register(&CacheRule{}, &CacheRuleList{})
}
