apiVersion: castai.upbound.io/v1alpha1
kind: EksCluster
metadata:
  name: sample
  labels:
    cast-ai-cluster: sample
spec:
  forProvider:
    accountId: "123456789101"
    name: sample
    region: eu-central-1