apiVersion: castai.upbound.io/v1alpha1
kind: EnterpriseServiceAccount
metadata:
  name: sample
spec:
  forProvider:
    enterpriseId: "<enterprise-id>"
    organizationId: "<child-organization-id>"
    name: sample-service-account
    description: Service account managed by Crossplane in a child organization
  providerConfigRef:
    name: default
