name: Promote

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. v0.1.0)'
        required: true
      channel:
        description: 'Release channel'
        required: true
        default: 'alpha'

env:
  # Common users. We can't run a step 'if secrets.AWS_USR != ""' but we can run
  # a step 'if env.AWS_USR' != ""', so we copy these to succinctly test whether
  # credentials have been provided before trying to run steps that need them.
  CONTRIB_DOCKER_USR: ${{ secrets.CONTRIB_DOCKER_USR }}
  AWS_USR: ${{ secrets.AWS_USR }}

jobs:
  promote-artifacts:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          submodules: true

      - name: Fetch History
        run: git fetch --prune --unshallow

      - name: Login to Docker
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3
        if: env.CONTRIB_DOCKER_USR != ''
        with:
          username: ${{ secrets.CONTRIB_DOCKER_USR }}
          password: ${{ secrets.CONTRIB_DOCKER_PSW }}

      - name: Promote Artifacts in S3 and Docker Hub
        if: env.AWS_USR != '' && env.CONTRIB_DOCKER_USR != ''
        run: make -j2 promote BRANCH_NAME=${GITHUB_REF##*/}
        env:
          VERSION: ${{ github.event.inputs.version }}
          CHANNEL: ${{ github.event.inputs.channel }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_USR }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PSW }}
